### ISSUE TITLE
How adapter trimming works?

### ISSUE THREAD

**Issue by githubholiday** [OpenGene/fastp#1]
I'd like to know how adapter trimming works? Both for single end and paired end data.

**Comment by sfchen** [comment]
Adapters only exist in 3' end.  
Adapter trimming only cut the adapters, and will not discard the reads.

For single-end data:
1, fastp is like cutadapt, but faster. Error tolerance is enabled. One mismatch is allowed for 8 bp overlap.
2, if part of adapter matches the tail of the read, the adapter is trimmed.

For paired end data:
Adapters is detected using overlap analysis. See the AfterQC paper.

**Comment by TuBieJun** [comment]
Hi ,I  have saw the source of   adapterimmer ,  the principle is to allow the maximum number of diff to find the largest PE reads overlap sequence, the rest as an adapter to remove. But there is a problem is to compare PE reads base. If the same time, if R1 has a wrong indel, then cause the following bases are different with R2, resulting in diff the number increases, so overlap length decreases, the adapter can not be removed.
So  can you add a argument to consider wrong indel in next version.

**Comment by sfchen** [comment]
Closing this since this is not an issue
