### ISSUE TITLE
Discrepancy in results between screen output and report out

### ISSUE THREAD

**Issue by BenoitFiset** [OpenGene/fastp#10]
Hi,

  Trying to figure out the onscreen results when fastp finishes running and the results summary in the generated report file.

The numbers don't addup.... 

Thanks for the help.

================
Example when fastp finishes and the output on screen gives:
================
Read1 before filtering:
total reads: 4000000
total bases: 400000000
Q20 bases: 392516035(98.129%)
Q30 bases: 376358571(94.0896%)

Read1 after filtering:
total reads: 3102308
total bases: 309754624
Q20 bases: 306341522(98.8981%)
Q30 bases: 294745910(95.1546%)

Read2 before filtering:
total reads: 4000000
total bases: 400000000
Q20 bases: 387859490(96.9649%)
Q30 bases: 373512577(93.3781%)

Read2 aftering filtering:
total reads: 3102308
total bases: 309754624
Q20 bases: 305723840(98.6987%)
Q30 bases: 295222362(95.3085%)

Filtering result:
reads passed filter: 6204616
reads failed due to low quality: 235470
reads failed due to too many N: 1559914
reads failed due to too short: 0
reads with adapter trimmed: 1355796
bases trimmed due to adapters: 17275112

=================================
These are the results in the report:
=================================
fastp report
Summary
General
fastp version:	0.7.0
sequencing:	paired end (100 cycles + 100 cycles)

Before filtering
total reads:	7.629395 M
total bases:	762.939453 M
Q20 bases:	744.224095 M (97.546941%)
Q30 bases:	715.132854 M (93.733893%)

After filtering
total reads:	5.917183 M
total bases:	590.810059 M
Q20 bases:	583.711016 M (98.798422%)
Q30 bases:	562.637589 M (95.231552%)

Filtering result
reads passed filters:	5.917183 M (77.557700%)
reads with low quality:	229.951172 K (2.943375%)
reads with too many N:	1.487650 M (19.498925%)
reads too short:	0 (0.000000%)

**Comment by sfchen** [comment]
Good catch! 

On-screen display should be 4000000 pairs = 8000000 Reads.

8000000 Reads = 7.629395 M

8000000 / 1024 / 1024 = 7.629395

I will change on-screen display to be as same as the report.

Thanks
