### ISSUE TITLE
Option for report files names matched to input data files names

### ISSUE THREAD

**Issue by jandreslopez** [OpenGene/fastp#100]
Name report files by input file(s) to facilitate downstream analyses of filtering procedure (matching the equivalent FASTQC behavior).

**Comment by sfchen** [comment]
But I think you can achieve this easily using your scripts to make the command line to call fastp, right?

**Comment by KimBioInfoStudio** [comment]
yep, using optional name for .html and .json is little case for some users, but it really is not friendly for new beginner, if there are several fastq input file ,i use fastp twice in the same path, the html and json will be overwrote.

**Comment by jandreslopez** [comment]
I am sure you are right.  I am not an expert user so I normally just call fastp commands from a batch file to filter/trim a collection of files in a folder so at the end only the report for the last file processed is there.  I had gotten used to the fastqc behavior that produced report files for each processed fastq file.

**Comment by sfchen** [comment]
I will add this feature in future release.

**Comment by jsan4christ** [comment]
Am curious about the progress with this feature, I would like to run something like this: parallel 'fastp -i {}_1.fastq.gz -I {}_2.fastq.gz -o fastp_out/matepairs/{}_1.fastq.gz -O fastp_out/matepairs/{}_2.fastq.gz -m  --merged_out fastp_out/merged/{}fastq.gz  -f 3 -t 2' ::: $(ls *.fastq.gz | rev | cut -c 12- | rev | uniq) but will only end up with the report for the last file.
