### ISSUE TITLE
discard or cut

### ISSUE THREAD

**Issue by flystar233** [OpenGene/fastp#104]
My sequences were cut when use default options -i -I  -o -O .

![tim 20181101152210](https://user-images.githubusercontent.com/20431495/47838340-06256580-ddea-11e8-8e71-1bb5ca4f537d.png)
![tim 20181101152226](https://user-images.githubusercontent.com/20431495/47838346-0aea1980-ddea-11e8-8720-d2cff4aefaa4.png)
In my opinion, Only when I use option -3 or -5 ,my sequences will be cut.

**Comment by sfchen** [comment]
It may be due to adapters.

You can add -A option to disable adapter trimming
