### ISSUE TITLE
XX% reads found not overlapped.

### ISSUE THREAD

**Issue by flystar233** [OpenGene/fastp#105]
HI
When using fastq, I found that a large number of sequences were not found overlap, and my data insertion fragment was 300 BP and PE150 sequenced. Can you tell me why?
![tim 20181101165359](https://user-images.githubusercontent.com/20431495/47842121-c0bb6500-ddf6-11e8-9f5f-23f0892df4bd.png)

**Comment by sfchen** [comment]
Your templates are too long.

For PE150 data, if your template is longer than 270, it will not be able to be detected as overlapped since 30 bases overlapping is required.
