### ISSUE TITLE
process all files in directory

### ISSUE THREAD

**Issue by lmanchon** [OpenGene/fastp#106]
--Hi,

for paired-end reads it will be usefull to add an option to process all files in a directory, as AfterQC does.

thank you --

**Comment by Cumol** [comment]
A bash script with a for loop does the trick. Here is an example:

```
#!/bin/bash
for f1 in *_1_sequence.fq.gz
do
        f2=${f1%%_1_sequence.txt.gz}"_2_sequence.fq.gz"
        fastp -i $f1 -I $f2 -o "trimmed-$f1" -O "trimmed-$f2"
done
```
This outputs two files with the trimmed- tag on each. It assumes that fastp is in your $PATH

You can run it using `source script.sh` from the command line.

**Comment by vishalsnegi** [comment]
Shouldn't the 'txt' in `{f1%%_1_sequence.txt.gz}` be 'fq'  `{f1%%_1_sequence.fq.gz}`
