### ISSUE TITLE
Non-determinism?

### ISSUE THREAD

**Issue by jthreefoot** [OpenGene/fastp#108]
Hello,

I’m working on a genomics analysis pipeline. We use fastp before our alignment and further analysis. I recently discovered that there seems to be some randomness in fastp’s output. I tried running fastp several times on the same pair of FASTQs and got the md5 hash of the resulting file each time. These were my results:

```
R1: a105a5a858e99989b78d0e1c3958296d | R2: 5cb80d0dd6d4b6a68f18ba6dae0c253b 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: a105a5a858e99989b78d0e1c3958296d | R2: 5cb80d0dd6d4b6a68f18ba6dae0c253b 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
R1: 3d44196675b9e903b9094bc37707c682 | R2: d0dd697eb44f6f00a8ef0e1e1c448d91 
```

I can’t find any documentation about nondeterminism in fastp, and grepping the code didn’t find any obvious use of randomness. Do you know what could be causing this?

Attached is the script I used (as a .txt file because GitHub won't allow .sh files to be attached here) to get the above and the FASTQ pair I ran it on (the FASTQs are tiny in-silico files I was using for software testing).

[fastp-variance-test.txt](https://github.com/OpenGene/fastp/files/2587096/fastp-variance-test.txt)
[epc-fail-2_S1_R1_001.fastq.gz](https://github.com/OpenGene/fastp/files/2587076/epc-fail-2_S1_R1_001.fastq.gz)
[epc-fail-2_S1_R2_001.fastq.gz](https://github.com/OpenGene/fastp/files/2587077/epc-fail-2_S1_R2_001.fastq.gz)

Thank you.

Best,
Jane

**Comment by sfchen** [comment]
Due to multi-threading fastp doesn't keep the order of reads, so it will cause different MD5.

But don't worry, it has 0 effect for the downstream analysis since no software relies on the order of reads.

If you still have concern, you can specify `-w 1` to use only one thread.

**Comment by jthreefoot** [comment]
Ah, ok, that explains it.

After fastp, we run bwa, and according to https://www.biostars.org/p/238628/ bwa does have randomness that can result in different results from different input read orders.

We may end up running fastp single-threaded; we're figuring out the extent of the impact and performance trade offs.

Thank you for your help!
