### ISSUE TITLE
issue when filtering empty reads

### ISSUE THREAD

**Issue by phil-grayson** [OpenGene/fastp#111]
Hi, 

The most recent batch of RNA-seq data that I've received back has a small number of completely empty reads (which could potentially be the result of some over-clustering since I've never seen them before).  These reads are giving me problems in some downstream analysis steps.  I thought that your program would be a good solution for removing these and I gave it at try.  Here's an example with 4 reads:

```
@NS500422:705:HWFKTBGX5:1:11101:15654:1151 1:N:0:GATCTATC+AGCCTCAT
GGGTTATGTAGGAGTCAAATGAGAGGTCCTTGAAGTCT
+
AAAAAAEEEEEEEEEEEEEEEEEEEEEE/EEEE/EEE6
@NS500422:705:HWFKTBGX5:1:11101:18801:1152 1:N:0:GATCTATC+AGCCTCAT

+

@NS500422:705:HWFKTBGX5:1:11101:10924:1154 1:N:0:GATCTATC+AGCCTCAT
GCCCATCCAGGTGCTTGCAGGCTGAAAAGACCACGTGT
+
AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
@NS500422:705:HWFKTBGX5:1:11101:22690:1084 1:N:0:GATCTATC+AGCCTCAT
CCAGCNCATAACAGCAATGTAAGGCATGTTCACCCTG
+
AAAAA#EEEAAEEEEEEEEEEEEEEEEEEEEEEEEEE
```

If you create a fastq file with this and run: 
`./fastp -A -Q -i empty_example.fq -o length_filtered.fq`
 
You wind up with the following outfile:
```
@NS500422:705:HWFKTBGX5:1:11101:15654:1151 1:N:0:GATCTATC+AGCCTCAT
GGGTTATGTAGGAGTCAAATGAGAGGTCCTTGAAGTCT
+
AAAAAAEEEEEEEEEEEEEEEEEEEEEE/EEEE/EEE6
+
AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
@NS500422:705:HWFKTBGX5:1:11101:22690:1084 1:N:0:GATCTATC+AGCCTCAT
CCAGCNCATAACAGCAATGTAAGGCATGTTCACCCTG
```

My reads are paired-end (one empty read paired to a read with data) and running them in paired-end mode produced the same output as the above example with the single-end data above.  The program removes the empty read and the next two lines (header and sequence data for the read below), then it looks like it counts line 3 and 4 of that read as lines 1 and 2 going forward, so we end up with only the first two lines of the final read in the example (no "+" and no quality scores).

I'm not sure how common these empty reads are given that this is the first time I've encountered them, but for me, the simplest solution has been to run the following line of code to replace the empty lines with a single N, and then either run your program (which works normally) or go straight to the downstream analysis step.
`sed 's/^$/N/' empty_example.fq > empty_example_with_Ns.fq`

**Comment by sfchen** [comment]
I just added a change to skip the reads without a valid name, which should start with a `@`
