### ISSUE TITLE
QC only

### ISSUE THREAD

**Issue by lmanchon** [OpenGene/fastp#112]
--Hi,

is there an option to make QC only as AfterQC does with --qc_only parameter ?

thank you --

**Comment by sfchen** [comment]
If you don't specify `--out1` and `--out2`, it will be the QC only mode.

**Comment by sklages** [comment]
@sfchen - this means that omitting `--out1` and `--out2` is some kind of **"dry mode"**? So the plots and stats in  the "After filtering" sections show how the fastq **would** look like after applying the "real trimming/filtering" by supplying the output file parameters? That would be cool indeed :-)
