### ISSUE TITLE
output fastq is  not complete

### ISSUE THREAD

**Issue by StayHungryStayFool** [OpenGene/fastp#113]
My code:
I use fastp 0.19.5, because conda just support this version.
fastp -i $R --disable_adapter_trimming --disable_quality_filtering --length_required 15 -o $DIR/$Out

My Input tail 12 lines:
@ST-E00523:464:HTGVMCCXY:4:2224:25327:73282 2:N:0:GGCTAC
TATCAGTGGCCTCCTGTCTGCCTTGTCCCGGCCTCGCTTGAGTTGGGGCTGGAAGCTATCTATATTCACTTCCCCGCTGTGGGAGGCCCTTCAAATCCCTGCCACGTCACCTCACTCTGGTCCT
+
JFFJAAFJJJJJJJ<JAJJFJJFJJFJJJJFJJJJFJ<7<-AJFAJ<JJJJJ-A7FJJJJFAJ-JAF<FFFJ-FJ7JF-<FF<F)7JJJJFJ<<JAJFJFFJJ7A<7F-<<-A-<<FF-)<FF<
@ST-E00523:464:HTGVMCCXY:4:2224:26585:73282 2:N:0:GGCTAC
CAGGCAGAGACTCTTCGACGTCCGCCTCCCGGTCTCTCA
+
AAAFFJA<JFJJFJJJAFJF77---77A--7--7-F-F7
@ST-E00523:464:HTGVMCCXY:4:2224:26626:73282 2:N:0:GGCTAC
CAGGCAGAGACTCTTCGACGTCCGACTCTGGGTCTCTCACTGCTTAGTCTGGAAGAGGCTACTGAGGAAACCTGAAGACAT
+
AA-AF-7FA-<<FJJJJJJFJJ-7-A7JA-777F7FJJFJ-<F<<<--FA---A7<<7F-7FFJ7AA-7FJJA--7-7FJA

Out put tail 12 lines:
+
JF7AA-<-FJJF<AAFFAJ<<JJJFFAFJAJJF<JJJJJJJF-FJ7JJJ7<FFJJJJ<7-<-FJJFFJFJJJ7<JAFFF-A<F-)AFFFJAAJAAJAAJ7FJ-77AJ-<A-A77<<7FJA<<)-<F
@ST-E00523:464:HTGVMCCXY:4:2224:1955:72491 2:N:0:GGCTAC
TCTTCTTGTTTCTTCTTTGTGCGTGACTACTCAACAATCTGTGACCAACAACCAACAACTCACCACTCCTCTCTGGACCCCTAGCATTTATGTATCCTCTGAAAAGTCCTCAGAATTACAAACAT
+
JJJJJJJJFAJJJJJJJJJJFJJJJFJJJJJJJJJJJJJJJJFJJFJJJJFAJJFJJJJJJJJJJJFJJJJFJJAFJJFJJJJ<JFAAAJJFFJJJJJJFJFJJFJJJJFJJJAJFJFFJJJJJJ
@ST-E00523:464:HTGVMCCXY:4:2224:3194:72491 2:N:0:GGCTAC
CAGGCAGAGACTCTTCGACGTCGGACTCTGGGTCTCTCACTGCTTAGTCTGGAAGAGGCTACTGAGGAAACCTGAAGACATGAGTTAGGACAAGCTTATTTCTCCAAACCTAGACATCATTAAGCGGAAATTGTTCTTTCTAGACAGGT
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJAJJ
@ST-E00523:464:HTGVMCCXY:4:2224:3336:72491 2:N:0:GGCTAC
CAGGCAGAGACTCTTCGACGTCGGACTCTGGGTCTCTCACTGCTTAGTCTGGAAGAGGCTACTGAGGAAACCTGAAGACATGGCGGAACCATCTCAGGAAGAGCTCCTGCTAGGTTTCAGCTTCTCCTTGGTGGCTCTTGGCACAAA

I discovery this issue when i run bowtie2. Almost files look like this, so what should i do? Is this is a bug?

**Comment by sfchen** [comment]
Could you please add my wechat (opengene), I can debug with you.
