### ISSUE TITLE
Demultiplexing a Fastq file with Pacbio data, a mix of regular and reverse complimented sequences

### ISSUE THREAD

**Issue by dnk8n** [OpenGene/fastp#114]
I have this data that I would like to orientate consistently using a pair of barcodes per sample.

For each fastq record, I need to match it's sequence against each of my sample's forward and reverse barcode sequences. If no match I need to reverse complement the fastq record's sequence and try again. If a match the second time, I need to save that record in the reverse compliment order to a Fastq file per sample. If a match the first time, then save that record in the original sequence order to a Fastq file per sample.

Is this a feature worthwhile to you? In HIV research this form of demultiplexing is common. We seldom use shotgun sequencing and from what I gather (new to this job) many people each have their custom script to do the same thing.

I want to implement one way to do it. I tried Lima but was unsuccessful.

If I can explain any of the above better, please let me know. Also, I have not done much C/C++ development but am prepared to try (always been something on my list of to-dos).

Looking forward to your response :)

**Comment by dnk8n** [comment]
The saving of records in the correct orientation is a nice-to-have. My primary concern is demultiplexing by barcode pairs (I guess reverse complimenting the barcode pairs would be computationally less expensive than reverse complimenting the sequence in the case where you are not going to save the reverse complimented sequence upon a match).

What I could do for now is save to two files per sample. Sample1_original and Samole1_revcomp for example. I can generate barcode text files up front one with original barcodes, one with revcomp barcodes.

E.g

Sample1                  AGT TCT
Sample1_revcomp AGA ACT

Would this tool only write record to Sample1.fastq file if it matched AGT (at the beginning of sequence) And TCT (at the end of sequence).

I don't understand the format of barcode text file with regards to enzyme. It is not applicable to me. Do I insert 'Nan' in between those two barcodes?

**Comment by sfchen** [comment]
Currently fastp will not support this feature.
