### ISSUE TITLE
Missing header in pairwised filter

### ISSUE THREAD

**Issue by ZeweiSong** [OpenGene/fastp#115]
Hi,

I found that the output FASTQ contains missed header after pairwise filtering, liek this:

@V300010089L2C001R018264378/1
AAAGAAATTTAATAATTTTGAAAATGGATTTTTTTTTTTTGTTTGGGCAAGAGCATGAGAGCTTTTACTGGGCAAGAAGGCAAGAGTTGGAGAGTCCAGCCGGGCCTGCGCTTAGGTGGCCGGCCTTGCTAGGCTT
+
GF<GFF+GFE5EF>E>AFFGE/,<F<A;?>+><(FG<0F<E'@F(GFFG@F3AG>5G7@,==:)E=<:GF>9E:F/E3B(68FG7F,CGD.=8G-=98/FFFADB453G1CG3B+F=@0*@DF,EG@7D6,>B:G)
+
FFFECFFFCFFFEFEFFFFFFEFFFFFFFAFFDFBFDFCFAFFFFF>FFFFFFFFEF>FFFFFFF>EFFDABAFFFFFFEEFFFFE:=D0FGFFFFF;EEEFF.F>FFFFBFFDFFFF>GD6@FFDFFEF<DFF
@V300010089L2C001R018268234/1
GGTCATTTAGAGGAAGTAA
+
DBFBFFFFFFFF<FGDFFF

It seems that the second record got its header chop off for some reason, any ideas? This causes fatal error for downstreams.

p.s. I just noticed that the read number is also wrong, at least for the pairwise option.

Thanks!

**Comment by sfchen** [comment]
Is the FASTQ standard?
