### ISSUE TITLE
ERROR: the sequence of <adapter_sequence> should be 4 ~ 100 long

### ISSUE THREAD

**Issue by shenweima** [OpenGene/fastp#120]
SRR3089142.fastq.gz
Detecting adapter...
CAAGGATTGACAGACTGAGAGCTCTTTCTTGATTCTATGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGCGATTTGTCTGGTTAATTCCGTTAACGAACGAGACCT

ERROR: the sequence of <adapter_sequence> should be 4 ~ 100 long.

**Comment by sfchen** [comment]
I will fix this issue
