### ISSUE TITLE
In the process of Overrepresented sequence analysis, the list of sequences with relatively high occurrence frequency in different sizes is not accurate.

### ISSUE THREAD

**Issue by liumeiyang** [OpenGene/fastp#123]
The step 1 in the process of Overrepresented sequence analysis, you use a map to store kmers and iterate map to remove substrings(kmers). But it is sorted by lexicographic order, not by the length of kmer. So in my opioion the result is not accurate.

**Comment by sfchen** [comment]
The top 10 overrepresented sequences are selected by weighting the `sequence length` and `repeat times` together.
