### ISSUE TITLE
Can fastp handle a UMI tht is not located at the the head of the read?

### ISSUE THREAD

**Issue by john-s-f** [OpenGene/fastp#124]
For example, if I have a library structure like this
`5'illumina - 4 random nucleotides - insert - 5 random nucleotides - 5 nucleotide UMI - 3'illumina`
Am I able to tell fastp where the location of the UMI is?

**Comment by sfchen** [comment]
Do you want to extract all `4 random nucleotides`, `5 random nucleotides` and `5 nucleotide UMI`, or just `5 nucleotide UMI`?

Is your data paired-end or single-end?
