### ISSUE TITLE
qualified quality filtering sometimes discards one read in pair

### ISSUE THREAD

**Issue by isthisthat** [OpenGene/fastp#125]
I'm trying to use fastp to only do qualified quality filtering (disabling all other default filtering). My commandline looks like this:  

    fastp_0.19.4/fastp -i R1.fastq.gz -I R2.fastq.gz -o R1_fp40.fastq.gz -O R2_fp40.fastq.gz -A -G -L -u 40

My aligner sometimes complains that there's a read name mis-match between read1 and read2 which I suspect means that either the fastq sort order has changed or that one read has been filtered but not the other. I can confirm that the aligner does not complain on the original data, only the fastp filtered data of the above command.

Thank you for your help and for this brilliant software!

**Comment by sfchen** [comment]
For PE data, fastp keeps or discards both pairs of reads.

Can you please upload some test data so that I can do some investigation?

**Comment by isthisthat** [comment]
Closing for now since I haven't had time to investigate. Will re-open if I find a concrete example. Thanks for your response.
