### ISSUE TITLE
GC content filter

### ISSUE THREAD

**Issue by katosh** [OpenGene/fastp#127]
It would be nice if there were a filter based on the read GC-content as suggested in #76. This filter could be used in addition to the low complexity filter. While the complexity defined in the existing filter for pure GC reads, e.g., `GCGCGCGCGCGC` is 100%, since there are no same bases next to each other, the reads are insufficiently "complex" to align uniquely.

I imagin a way to define GC content could be the percentage of neighboring pairs `base[i]` and `base[i+1]` for which:
```
(base[i] == 'G' & base[i+1] == 'C') | (base[i] == 'C' & base[i+1] == 'G')
```

**Comment by sfchen** [comment]
Why would you like to have a such `CpG` filter? Is it for methylation data analysis?

Could you please show me some cases that it will be helpful?

**Comment by katosh** [comment]
Using the pseudoalignments of [kallisto](https://pachterlab.github.io/kallisto/about) revealed an abundancy peak for alignments of template length 31 bp that seems to originate from polyA and (almost) pure GC reads. Each of these reads aligns to the same n position in the chosen transcriptome. I hoped to remove the artifact with fastp filters. Sadly the respective project was put on ice for other reasons.

**Comment by sfchen** [comment]
No, @katosh , this project is not on ice. I am intensively developing to provide new functions. Yesterday I just released v0.19.10

But this GC content filter, seems not commonly wanted, so I decided not to implement it to make fastp simple and easy.

If you want to filter polyA, you can use the newly introduced --adapter_fasta to add polyA in a adapter FASTA file.

And for GC, I suspect that they are most G, right?

NovaSeq / NextSeq likes to have much more polyG, and you can filter it by polyG filter.

**Comment by katosh** [comment]
Sorry, I did not mean the fastp project but our project that I am involved in that was put on ice. I thank you for the support and I would like to continue working with fastp at a later time.

Concerning the reads: They mostly looked like `GCGCGCGCGCGCGC` with occasional defects in the chain.  We expect those reads but wanted to ignore them and other ones with too little complexity in the mentioned study.

**Comment by zaustinj33** [comment]
Hi, I would like to revisit this topic. I work with methylation data where the expected proportion of methylated bases ("C" on R1 and "G" on R2) is much lower compared to the other nucleotides. We would like to observe differences between reads with high and low methylated base content, or have the option to remove reads with high content altogether (as these are likely to be false positives). 

Something similar to `--n-base-limit` but a specified base would be fantastic.

Thank you
