### ISSUE TITLE
multiple threads -w not work

### ISSUE THREAD

**Issue by cafeblue** [OpenGene/fastp#13]
Even set -w to a different number, the program consist running in 3 cores...

**Comment by sfchen** [comment]
How did you know that didn't work? Did you check the thread number in tools like task manager?  3 worker threads mean 6 thread in total.

If you set `-w 5`, you may see 8 threads.

Be noted that `fastp` is so fast that if you set too many threads, it will have bottlenecks in I/O, so the CPU usage will be not increased.

**Comment by sfchen** [comment]
Closing
