### ISSUE TITLE
Blank/missing reads in FASTQ cause malformed output FASTQ

### ISSUE THREAD

**Issue by dgroot** [OpenGene/fastp#133]
If one of the input FASTQ files has a missing/blank sequence, the output FASTQ will be malformed.

I.e. if the input FASTQ has a correct entry followed by a blank entry like this:
```
@A00545
ACGTGCTGAC
+
FFF,:,FFFF
@A00546

+

```
where the sequence line and quality line are both blank, then the output will have a malformed entry, like so, where there is only a "+" and a quality sequence, but no read ID or genetic sequence:

```
@A00545
ACGTGCTGAC
+
FFF,:,FFFF
+
F:FFFFFFFF
```

The program should either throw an error if the FASTQ file has a blank entry, or skip the entry entirely in the output.

(In this case, I didn't know my FASTQ file had a blank entry—it came off the sequencer like that—but Fastp ran with no errors and I only discovered the problem during downstream analysis because the output FASTQ file was not correctly formed.)

**Comment by sfchen** [comment]
I will fix this issue in next version

**Comment by sfchen** [comment]
I think each valid FASTQ record should start with the ID row, which starts with an `@` . Do you agree?

**Comment by sfchen** [comment]
I just add a commit to skip the reads without a valid name, which should start with an `@`

**Comment by dgroot** [comment]
No, this will not fix the issue. You can see in my example, on line 5, there is a correct "@" symbol and valid ID line, but the sequence line and the quality sequence line are empty, and in the output, it gives only 2 lines for that entry instead of 4 lines, so the whole output is wrong.

So it needs to check that those are not empty, you cannot just check the header name.

**Comment by sfchen** [comment]
I've added a commit to handle the blank lines.

It should be already fixed now. Please try the new v0.19.7

**Comment by sfchen** [comment]
closing
