### ISSUE TITLE
Trim poly-G 

### ISSUE THREAD

**Issue by chenyj8** [OpenGene/fastp#138]
Hi,

Poly-G might appear at any position when using NextSeq/NovaSeq, but fastp seems to only trim poly-G at the read tail. Would it be possible to perform poly-G trimming at any position?

Thank you.

**Comment by sfchen** [comment]
The poly-G in the middle of reads are usually with low quality.

You can use `--cut_right` to trim them

**Comment by chenyj8** [comment]
> The poly-G in the middle of reads are usually with low quality.
> 
> You can use `--cut_right` to trim them

Thanks. AfterQC can trim the poly-G with a sliding window. Is that correct?

**Comment by sfchen** [comment]
Yes, but actually most polyG are in the tails, as far as I know.
