### ISSUE TITLE
Request: supporting for amplicon sequencing

### ISSUE THREAD

**Issue by lozybean** [OpenGene/fastp#14]
Amplicon sequencing using a set of artificial, amplicon-specific primer. If a reads is beginning with this primer, it is a target reads, and artificial primer should be removed. Otherwise it should be filtered.

**Comment by sfchen** [comment]
Would you please upload two small files so that I can test:
1, a amplicon-seq FASTQ file
2, the corresponding primer list file

**Comment by lozybean** [comment]
Hi, 
here is some test data:
[amplicon_data.tar.gz](https://github.com/OpenGene/fastp/files/1520551/amplicon_data.tar.gz)

Thanks.

**Comment by sfchen** [comment]
OK, but low priority.

**Comment by lozybean** [comment]
thanks and take your time.

**Comment by lozybean** [comment]
Another request:
would you please add GC content in summary section?

**Comment by sfchen** [comment]
I'll add GC content in summary info.

**Comment by marchoeppner** [comment]
JUst came across this when trying to understand whether fastP would work on amplicon data - I take it it doesn't and that this issue is still unadressed?

**Comment by sfchen** [comment]
fastp already supports amplicon-seq data.
