### ISSUE TITLE
merge option

### ISSUE THREAD

**Issue by SilvanoS** [OpenGene/fastp#148]
Dear Author, 
I'm trying to use the merge function but I get an error: 
undefined option: --merge 
or 
undefined option: -m 

actually the option seems not be present in the option list. I'm using the last fastp version 
(attached a file that shows version and option of my installed fastp.

Am I doing something wrong on how to use it? What should be the correct structure of the command line? (I tried something like that):
fastp -i in.R1.fq.gz -I in.R2.fq.gz -m -o out.R_merged.fq.gz 

Thank you very much in advance for your help!
[fastp_report.txt](https://github.com/OpenGene/fastp/files/3014229/fastp_report.txt)

**Comment by sfchen** [comment]
Hi the merge function was just introduced I the new version v0.19.8, which has not been released.

If you want to try it, please compile fastp from the latest code, or download the prebuilt version from https://opengene.org/fastp/fastp

**Comment by SilvanoS** [comment]
Dear Shifu,
thank you so much for your reply!

Kind regards.
