### ISSUE TITLE
%GC content

### ISSUE THREAD

**Issue by BenoitFiset** [OpenGene/fastp#15]
Hi,

  would it be possible to add a calculated %GC content on the base contents graphs near the base index (top right) ?

Thanks

**Comment by sfchen** [comment]
It's possible.

But how about adding this info in the top summary table?

**Comment by BenoitFiset** [comment]
I thought about that before asking, but for the the informative function, it would be more ergonomic to have it near where the data is graphed.

Doesn't preclude to not put it in the summary, but if you go that route It would be nice to now have 2 sections in the summary, one for each read when doing paired reads.  :)

Thanks.

**Comment by sfchen** [comment]
Good suggestion, I will implement it.

**Comment by sfchen** [comment]
Hi, this is implemented!

Please try the latest v0.11.0

**Comment by BenoitFiset** [comment]
Wow... really nice with the GC.  Cosmetic thing, the right parenthesis seems half cropped on the image after the % sign. 

Nice addition also with the KMER table.

**Comment by sfchen** [comment]
Aha...yes, I will figure out how to fix that.

**Comment by sfchen** [comment]
If you have any feature request, please file new issues.

I will implement `overrepresented sequence analysis` in following step.
