### ISSUE TITLE
Filtering on mean quality per sequence

### ISSUE THREAD

**Issue by jpflorido** [OpenGene/fastp#152]
Is there any plan to include a filtering option for removing reads whose mean quality is below a threshold (similar to AVGQUAL in Trimmomatic)?
Thanks

**Comment by sfchen** [comment]
It's not complicated to implement it.

But I'd like to know anybody else wants this feature?

If many people want it, I can make it.

**Comment by fortuno** [comment]
That would be very helpful! 

Given that fastp is clearly faster than Trimmomatic having similar functionality like the filter by mean quality will help users to finally decide moving to fastp ;-)

**Comment by cfsancas** [comment]
I'm agree with @fortuno. I'm thinking to moving from trimmomatic to fastp in my pipelines and similar features will help to do it.

**Comment by sfchen** [comment]
Ok, I will implement this feature soon.

Could you please also tell me that what other features you usually use in Trimmomatic, but not provided in fastp?

**Comment by fortuno** [comment]
Thanks @sfchen !
For now, I think that is the only functionality I currently miss from what I am using in Trimmomatic.

**Comment by jpflorido** [comment]
Thanks! Sliding window (which is implemented already) and mean quality are my usual filters for Trimmomatic.

**Comment by sfchen** [comment]
Just submitted a commit to support this feature

**Comment by sfchen** [comment]
You guys can try the latest prebuilt, or compile from source.

`-e, --average_qual` if one read's average quality score <avg_qual, then this read/pair is discarded. Default 0 means no requirement (int [=0])

**Comment by jpflorido** [comment]
Thanks! I've tried using just --average_qual as filtering step for PE data, but -o output is not generated (-O, --unpaired1 and --unpaired2 outputs are correctly generated)

**Comment by sfchen** [comment]
> Thanks! I've tried using just --average_qual as filtering step for PE data, but -o output is not generated (-O, --unpaired1 and --unpaired2 outputs are correctly generated)

Can you show your command and the output folder?

**Comment by jpflorido** [comment]
Sorry, the command was wrong (-o output wasn't correct). The new filtering option works well! Go ahead for the new release.
Thank you very much!
