### ISSUE TITLE
No adapter detected but 

### ISSUE THREAD

**Issue by olferievm** [OpenGene/fastp#153]
Dear Authors,

Could you please clarify it for me? I have a pair of fastq files with adapters  trimmed by NGS facility. As was expected the adapters were undetected, ...but there were 5743820 reads with adapter trimmed.
`
fastp -i IF-0029V16_1.fq.gz -I IF-0029V16_2.fq.gz \
 -o ~/Trim/IF-0029V16_1.fq.gz -O ~/Trim/IF-0029V16_2.fq.gz \
  --html ~/Trim/IF-0029V16.html --json ~/Trim/IF-0029V16.json \
 --report_title ~/Trim/IF-0029V16.txt  \
 --detect_adapter_for_pe \
 --trim_poly_x \
 --correction \
 --thread 16 \
 --dont_overwrite \
 --length_required 36`

```

Process IF-0029V16
Detecting adapter sequence for read1...
No adapter detected for read1

Detecting adapter sequence for read2...
No adapter detected for read2
```
```
Filtering result:
reads passed filter: 126835844
reads failed due to low quality: 1411636
reads failed due to too many N: 333694
reads failed due to too short: 34642
reads with adapter trimmed: 5743820
bases trimmed due to adapters: 64967338
reads corrected by overlap analysis: 2688890

bases corrected by overlap analysis: 3830916
Duplication rate: 9.66233%
Insert size peak (evaluated by paired-end reads): 130

```

**Comment by sfchen** [comment]
```
reads with adapter trimmed: 5743820
bases trimmed due to adapters: 64967338
```
By average, one read was trimmed with only 10bp adapter.

This is very short, seems that your data contains some short adapter contamination, that was not trimmed well by previous tool.

Although adapter sequence is not detected, fastp can still trim adapter by detecting overlapping regions of PE reads.

**Comment by sfchen** [comment]
Can you share the HTML report here?

**Comment by olferievm** [comment]
Thank you for the fast reply,

It is interesting that fastp can find adapters in that case, but worried me that my RNA-seq provider didn't remove adapter sequences completely. Attached please find the associated html report as a pdf file.

Would it be beneficial to provide fastp with the adapter sequences in my case?

Mike.
[HD-0018V02.pdf](https://github.com/OpenGene/fastp/files/3100198/HD-0018V02.pdf)

**Comment by sfchen** [comment]
I checked your report. The adapters are true Illumina TruSeq adapter.

**Comment by olferievm** [comment]
Thank you for clarifications.

**Comment by sfchen** [comment]
```
Would it be beneficial to provide fastp with the adapter sequences in my case
```
Providing the adapter sequences may improve a little, but not much.

**Comment by sfchen** [comment]
Enjoy fastp.
