### ISSUE TITLE
Q20 or Q30 ratio

### ISSUE THREAD

**Issue by skenoy** [OpenGene/fastp#16]
can you add Q20 or Q30 ratio every position in xxx.json

**Comment by sfchen** [comment]
Ok, this feature will be considered.

**Comment by whiteorchid** [comment]
hi, is it convenient to add the Q10, thanks very much and best wishes!

**Comment by sfchen** [comment]
@whiteorchid why you need Q10 stat? For what kind of data?

**Comment by whiteorchid** [comment]
thought it can be an useful  info, for fastq stat.
