### ISSUE TITLE
Sum of read numbers of sub files is not equal to the input files

### ISSUE THREAD

**Issue by xie186** [OpenGene/fastp#162]
I'm using `fastp` to split the input (1M PE reads) into 20 sub files. But in the outputted files, there were only 977838. What's the reason? Is it possible to keep all the reads in the sub files? Thanks.

**Comment by xie186** [comment]
I figured out the reason. The reason is that fastp will do filtering based on base quality. This will remove some reads. The filtering could be disabled using `--disable_quality_filtering`

**Comment by RajneeshSrivastava** [comment]
Hi Team,
With the same situation mentioned by Xie, what will happen if the paired end files doesn't contain equal/ordered read mates. Does fastp split command take care of the sequence IDs while splitting the PE fastq files? I would expect, after splitting sample_1-001_R1.fastq and sample_1-001_R2.fastq files should have reads only for matched ID.

Thanks, 
Rajneesh
