### ISSUE TITLE
Is it possible to only produce the report, without output fastq files.

### ISSUE THREAD

**Issue by mken418** [OpenGene/fastp#164]
Hello, 

I was wondering if it is possible to use fastp in some cases as a much faster FastQC. I see that I can turn off adapter trimming and quality trimming (-A, -Q), and thus fastp won't trim my inputs and only output report. Is it possible for fastp to do this without outputting the fastqs afterwards?

**Comment by hauduc** [comment]
Output fastq files into /dev/null ?
