### ISSUE TITLE
undefined option: --detect_adapter_for_pe

### ISSUE THREAD

**Issue by ereverman** [OpenGene/fastp#178]
Hi,

I've used this code in the past without issue, but now, the --detect_adapter_for_pe is throwing an error. Here is the code chunk:

  activate_conda_environment ${PROJECT} fastp

  fastp -i ${DATA_RAW}/${sample}_R1_*.fastq.gz \
        -I ${DATA_RAW}/${sample}_R2_*.fastq.gz \
        -o ${DATA_FILT}/${sample}.R1.filt.fastq.gz \
        -O ${DATA_FILT}/${sample}.R2.filt.fastq.gz \
        -h ${FASTP_REPORTS_DIR}/${sample}.fastp.report.html \
        -j ${FASTP_REPORTS_DIR}/${sample}.fastp.report.json \
        -w ${N_THREADS} \
        --detect_adapter_for_pe \
        --correction \
        --cut_by_quality3 \
        --cut_window_size 5 \
        --cut_mean_quality 30 \
        --overrepresentation_analysis || { echo "fastp failed" ; exit 1; }
  source deactivate

Here is the error message:
undefined option: --detect_adapter_for_pe

Thanks

**Comment by sfchen** [comment]
You may be using the older version.

What's the version number?

**Comment by ereverman** [comment]
I am using version 0.14.1-0. How do I update to the current version?

**Comment by sfchen** [comment]
You should download the new version, or update using conda

**Comment by ereverman** [comment]
When I try updating with conda or reinstalling, the version number doesn't change.
