### ISSUE TITLE
ld returned 1 exit status while make 

### ISSUE THREAD

**Issue by biofuture** [OpenGene/fastp#18]
fastqreader.cpp:32: undefined reference to `gzoffset'
./obj/peprocessor.o: In function `PairEndProcessor::initOutput()':
peprocessor.cpp:35: undefined reference to `gzbuffer'
peprocessor.cpp:38: undefined reference to `gzbuffer'
collect2: error: ld returned 1 exit status
make: *** [fastp] Error 1

**Comment by sfchen** [comment]
Your zlib is too old, two options:
1, update your zlib
2, use the pre-built fastp from http://opengene.org/fastp/fastp

**Comment by biofuture** [comment]
Still cannot make after the update the zlib. But I can use the binary version you supplied firstly. Thanks

**Comment by sfchen** [comment]
The pre-built version is statically linked, so you don't need to have zlib installed.

**Comment by sfchen** [comment]
Closing
