### ISSUE TITLE
Error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by haiwufan** [OpenGene/fastp#19]
Dear Developer,
I have PE fastq file,  R1.fq + R2.fq have 34225961 pairs reads, total bases 10.2G, and R1.fq file size 12Gb.
When I run fastp command:
fastp -i R1.fq -I R2 -o trim.R1.fastq.gz -O trim.R2.fastq.gz  -5 -3 -M 30 -q 30 -l 36 -n 5 -c --html trim.html --json trim.json --report_title "Fastp Report" --thread 10 > trim.log
found error "Segmentation fault (core dumped)".

but when I remove the one of '-5' or '-3' option, there is no error reported.

So I abstract 100000 read and build test.1.fq and test.2.fq, and run fastp with the same command:
fastp -i test.1.fq -I test.2.fq -o trim.R1.fastq.gz -O trim.R2.fastq.gz  -5 -3 -M 30 -q 30 -l 36 -n 5 -c --html trim.html --json trim.json --report_title "Fastp Report" --thread 10 > trim.log
It run ok without error.

How can I solve this problem?

**Comment by sfchen** [comment]
I will check with the sliding window cutting by quality. 

Thanks

**Comment by sfchen** [comment]
I just update the code to fix this issue, please try the latest version and update here.

Big thanks for your contribution.

**Comment by haiwufan** [comment]
Thanks sfchen，
I will test the lastest version, thanks again.

**Comment by haiwufan** [comment]
Hi sfchen,
Today, I compared three software (fastp, cutadapt, trimmomatic) , and found fastp very fast but adapter cannot be remove clean.
I upload my result and hopefully you found this useful! 

[compare_software.xlsx](https://github.com/OpenGene/fastp/files/1574752/compare_software.xlsx)

**Comment by sfchen** [comment]
Thanks for the result, from the data, I can see:

* for short adapters (7bp), Trimmomatic removes the most adapter, then fastp removes less, and Cutadapt removes the least.
* for longer adapters (>7bp), fastp removes much more than Trimmomatic and Cutadapt.
* in total, fastp removes the most adapters.

Am I right?

**Comment by sfchen** [comment]
Can you try to grep the adapter sequence in those files?

Can you open another issue so we can track it with a new title, since the segmentation fault issue is already fixed.

Can you upload the first 10000 lines of the FASTQ files? So I can test it?

**Comment by sfchen** [comment]
Closing this issue.
