### ISSUE TITLE
About adapter trimmer

### ISSUE THREAD

**Issue by TuBieJun** [OpenGene/fastp#2]
Hi ,I have saw the source of adaptertrimmer , the principle is to allow the maximum number of diff to find the largest PE reads overlap sequence, the rest as an adapter to remove. But there is a problem is to compare PE reads base. If the same time, if R1 has a wrong indel, then cause the following bases are different with R2, resulting in diff the number increases, so overlap length decreases, the adapter can not be removed.
So counld you add a argument to consider wrong indel in next version.

**Comment by sfchen** [comment]
How about discard the pairs with wrong INDEL detected in PE assembly?

**Comment by sfchen** [comment]
Hi @TuBieJun , any update?
