### ISSUE TITLE
Addition in the summary part of the report

### ISSUE THREAD

**Issue by BenoitFiset** [OpenGene/fastp#20]
Hi,

  Can you put the "evaluated" adapter sequence in the top summary part of the report ?

Thanks,

B.

**Comment by sfchen** [comment]
Okay, but it will only be available for single-end data.

BTW, how do you think about `fastp` now, does it help for your work?

**Comment by BenoitFiset** [comment]
It's getting there... I guess once the trimming "tests" reach a conclusion, I should use more and more in production and forget about FastQC :)

Thanks for the quick turn over.

**Comment by sfchen** [comment]
Thank you!

**Comment by sfchen** [comment]
Implemented in the latest release v0.17.1
