### ISSUE TITLE
Undefined option --adapter_fasta

### ISSUE THREAD

**Issue by wul88** [OpenGene/fastp#210]
I got this error message when I ran fastp with a adapter file.
undefined option: --adapter_fasta

The fastp version is fastp 0.19.7. The conda download page indicated 0.20. but after I conda update, I still got the same version as before. 

Which version support the --adapter_fasta?

Thanks very much for a terrific tool!

**Comment by AndreaAguadoM** [comment]
Hello, how did you solved this issue? I am struggling with the same problem right now

**Comment by AndreaAguadoM** [comment]
Hello, how did you solve this issue? I am struggling with the same problem right now
