### ISSUE TITLE
fastp "Error to read gzip file"

### ISSUE THREAD

**Issue by RoskoDaneworth** [OpenGene/fastp#213]
Hi,
I'm trying to run fastp on WES .fastq.gz files but for each of them i get "Error to read gzip file".
The code im running is 

> cd $WES/input/
> for f in *_R1*; do
>    export R1="$(basename "$f")"
>    export R2=`echo "$(basename "$f")" | sed 's/_R1/_R2/'`
>    echo "found" "$R1" "$R2"
> done
> echo "input files are" "$R1" "$R2"
> 
> cd $WES/output
> fastp -i $R1 -o ${R1%%.*}_trimmed.fastq.gz -I $R2 -O ${R2%%.*}_trimmed.fastq.gz --unpaired1 ${R1%%.*}_unpair.fastq --unpaired2 ${R2%%.*}_unpair.fastq --failed_out ${R1%%_*}_failed.fastq -c --detect_adapter_for_pe -h fasp.html --dont_overwrite  -z 9 -w 8

I'd really like to use gziped files rather than decomp and raw fastq.
Is that an error on my side or else ? fastqc and trimmomatic used these files perfectly fine, but not fastp.
P.S. github detects some part of code as BBcodes so dont mind it please

**Comment by RoskoDaneworth** [comment]
Okay, seems like fastp dont like first part of code where it scans for R1/R2 files to use them later on.
When i manually written path and name it worked.
Guess i have to figure out how to rewrite it.

**Comment by sofiapuvogelvittini** [comment]
Hi, how did you solve this?
