### ISSUE TITLE
Compatible with MGISEQ fastq file

### ISSUE THREAD

**Issue by Gerde** [OpenGene/fastp#218]
Hi, 
       As  MGISEQ fastq file contain '/1 | /2' at the end of the read ID, after adding UMI information, it will cause an error while mapping with BWA-MEM:
       `[mem_sam_pe] [mem_sam_pe] paired reads have different names: "V300041225L2C001R0010000001/1:umi_TTCAC_TTAGA", "V300041225L2C001R0010000001/2:umi_TTCAC_TTAGA"`
       How can I deal with this problem ? 
       Thanks in advance !
Best,
Gerde

**Comment by sfchen** [comment]
Could you please paste some MGISEQ fastq reads here?

**Comment by Gerde** [comment]
Hi, sorry for not replying on time.  MGISEQ read name looks like this:
Read 1:
```
@v300022634L1C001R0040000003/1
TCTGAAGTCCTCCTCTCCAGAAGCCCTGCCCAAGAAGAGCCAACAGACTTCCTGAGCCGCCTTCGAAGATGTCTTCCCTGCTCCCTGGGGCGAGGAGCAG
+
F?FDCAEFCBEB@FAECC<A?D<84DFBAC>FC7E@<D>>DFFABDD:?D6=E7?@:@C<EEAA99=1CE=9EEE>>E?D/93>CED+56A>=;>@C><D
```
Read 2:
```
@v300022634L1C001R0040000003/2
ACGGTTCTGTCCTGAAGGCTGGTGCTAGAGACTCCACACAGCCACCCCCTAGCTGAGTGATCTTAAACTAGCACCTTATCCCGTGTTCTGCCGGCTTCAT
+
DDA?8<@FEAC8FD2?5C=DDD6BDE@<:CBCD@=EDE:<E?EEE?EDEBDDDEC<;=9B?3F:B5@>BEEC@5BEED68FE;@:@DD2F<E5ECAFBA@
```

**Comment by joshbridgers** [comment]
Additionally, the [old style](https://www.ncbi.nlm.nih.gov/sra/docs/submitformats/#older-illumina-fastq) Illumina read format produces the same error.

Format:
@<machine_id>:<lane>:<tile>:<x_coord>:<y_coord>#<index>/<read>

Read 1 and 2 example:
```
@HS26:339:H7MKKBCX3:1:1101:4290:1975/1 
@HS26:339:H7MKKBCX3:2:1101:1858:1984/2
```

**Comment by nordhuang** [comment]
latest fastp (version 0.20.1) already support this type fastq by adding --fix_mgi_id. 
for example, ./fastp -i R1.fq -I R2.fq -o O1.fq -O O2.fq --fix_mgi_id --umi --umi_loc=per_read --umi_len=4 --umi_prefix=UMI

**Comment by Gerde** [comment]
Thanks for all developers, it really helps !
I will close this issues, thanks !
