### ISSUE TITLE
How to remove adapter clean?

### ISSUE THREAD

**Issue by haiwufan** [OpenGene/fastp#22]
Hi sfchen,
Today, I compared three software (fastp, cutadapt, trimmomatic) , and found fastp very fast but adapter cannot be remove clean.
I upload my result and hopefully you found this useful!
[compare_software.xlsx](https://github.com/OpenGene/fastp/files/1577624/compare_software.xlsx)

sfchen commented:
Thanks for the result, from the data, I can see:

    for short adapters (7bp), Trimmomatic removes the most adapter, then fastp removes less, and Cutadapt removes the least.
    for longer adapters (>7bp), fastp removes much more than Trimmomatic and Cutadapt.
    in total, fastp removes the most adapters.

Am I right?

Replay:

Hi sfchen,
My sample real  adapter sequece is GATCGGAAGAGCACACGTCTGAACTCCAGTCAC********ATCTCGTATGCCGTCTTCTGCTTG, '*' is 8bp barcode.
And trimmomatic adapter file is : 
[adapter.list.xlsx](https://github.com/OpenGene/fastp/files/1577622/adapter.list.xlsx)

In the result table, I count the reads include adapter like this:

**Comment by haiwufan** [comment]
Hi sfchen,
My sample real  adapter sequece is GATCGGAAGAGCACACGTCTGAACTCCAGTCAC********ATCTCGTATGCCGTCTTCTGCTTG, '*' is 8bp barcode.
And trimmomatic adapter file is : 
[adapter.list.xlsx](https://github.com/OpenGene/fastp/files/1577622/adapter.list.xlsx)

**Comment by sfchen** [comment]
1, can you upload the first 10000 lines of the two files?
2, did Trimmomatic or Cutadapt cut adapters clean?

Thanks

**Comment by haiwufan** [comment]
Hi sfchen,
Test file : 
[Test.zip](https://github.com/OpenGene/fastp/files/1577640/Test.zip)

In my test, Trimmomatic or cutadapt cut adapter clean.

**Comment by sfchen** [comment]
But why they cut less adapters?

**Comment by haiwufan** [comment]
In my opinion, fastp remove adapters by overlap, that's not efficient method. 
cutadapt and trimmomatic cut adapter by string match, that's the different with fastp.

**Comment by sfchen** [comment]
Thanks for your opinion, the method for fastp to cut adapters for SE data is similar as cutadapt and trimmomatic. For PE data, we use overlap analysis since we think it's more efficient and faster.

but I need to understand why cutadapt and trimmomatic cut less adapters as I know from the table, but you said their result are cleaner?

**Comment by haiwufan** [comment]
maybe my description is not clear, I can share my perl script to you.
[stat_adapter.pl.txt](https://github.com/OpenGene/fastp/files/1578742/stat_adapter.pl.txt)

**Comment by haiwufan** [comment]
sfchen,
I run test data with cutadapt, trimmomatic, fastp.
[01_Cutadapt.tar.gz](https://github.com/OpenGene/fastp/files/1581332/01_Cutadapt.tar.gz)
[01_Fastp.tar.gz](https://github.com/OpenGene/fastp/files/1581333/01_Fastp.tar.gz)
[01_Trimmomatic.tar.gz](https://github.com/OpenGene/fastp/files/1581334/01_Trimmomatic.tar.gz)

**Comment by sfchen** [comment]
Thank you very much! I will test and update.

**Comment by yangyi0000** [comment]
Hi sfchen, I'm curious about the question,too. But this issue is closed, where can I access to the results please?

**Comment by var-chenm4680** [comment]
hello everyone,
I'm also curious about the question. When I used the Fastp but the adapter content shows that.[fig1]
However the FastQC is ok [fig2]

<img width="2194" height="1346" alt="Image" src="https://github.com/user-attachments/assets/2e38b1dd-86ac-461f-846e-7fcddae3226e" />

<img width="1774" height="616" alt="Image" src="https://github.com/user-attachments/assets/1fbdfcfe-f514-4a64-85ce-4ff40736f765" />
