### ISSUE TITLE
Why is 270 the maximum measurement limit for "Insert size estimation" ??

### ISSUE THREAD

**Issue by tetsuro90** [OpenGene/fastp#220]
Hi, 

It was very convenient when I used fastp.

but, my report says "88.524713% reads are with unknown length".
Certainly, since I experimented with a fragmentation size of 350 and 150PE, most reads would be longer than 270bp.
Why is 270 the maximum measurement limit for "Insert size estimation" ??
![newplot](https://user-images.githubusercontent.com/43412957/71089706-c7688f80-21e4-11ea-9107-132f6c653c85.png)

**Comment by sfchen** [comment]
Because fastp need at least 30 bp overlap to calculate the insert size of a DNA fragment.

300 - 30  = 270

**Comment by tetsuro90** [comment]
Hi, sfchen

thank you for your reply.
I understood the reason.

**Comment by jiapengatviome** [comment]
Why is 30bp the minimum limit for insert size estimation? What's the insert size estimation algorithm? Thanks.
