### ISSUE TITLE
Low-quality base trimming from leading and trailing side

### ISSUE THREAD

**Issue by wyzhangMPI** [OpenGene/fastp#24]
Hello,
     I have a question about the base trimming of fastp. Does it have an option for low-quality base trimming from both sides like in trimmomatic (LEADING and TRAILING options)? I would like to trim bad bases (Q<20) for both sides of the reads. 

The "--cut_by_quality5/3" in fastp and "Slidingwindow" option in trimmomatic seem quite different. The former would trim the reads in the window if with low-quality, while for the latter one if the low-quality bases are in the begining of the read, the whole read will the removed.

For example:
Input fq file: Test.fq (The last 4 bases for read 1 and first 4 bases for read 2 are bad ones)
@1\1
AATGATCGTAGCGATGCAAGCTAGCCCGATGCCCGATCGCATCG
+
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeEFCB
@2\1
AATGATCGTAGCGATGCAAGCTAGCCCGATGCCCGATCGCATCG
+
EFCBeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

##If run with LEADING and TRAILING options in Trimmomatic (Exactly what I want, the bad bases are removed)
>java -jar $Trimmomatic SE -phred64 Test.fq tt.fq LEADING:20 TRAILING:20
@1\1
AATGATCGTAGCGATGCAAGCTAGCCCGATGCCCGATCGC
+
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
@2\1
ATCGTAGCGATGCAAGCTAGCCCGATGCCCGATCGCATCG
+
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

##If run with Slidingwindow option in Trimmomatic (The 2nd read will be removed totally, as the bad bases are in the begining of the read)
>java -jar $Trimmomatic SE -phred64 Test.fq tt.fq SLIDINGWINDOW:4:20
@1\1
AATGATCGTAGCGATGCAAGCTAGCCCGATGCCCGATCGC
+
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

## If run with "--cut_by_quality5/3" in fastp (it is wierd that only the last 2 bases for read 1 and first 2 bases for read 2was clipped off)
>fastp --phred64 --in1 Test.fq --out1 Test_Trimed.fq --cut_by_quality5 --cut_by_quality3 --cut_window_size 4 --cut_mean_quality 20
@1\1
AATGATCGTAGCGATGCAAGCTAGCCCGATGCCCGATCGCAT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF&'
@2\1
GATCGTAGCGATGCAAGCTAGCCCGATGCCCGATCGCATCG
+
#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

Thanks!

Best,
Wenyu

**Comment by sfchen** [comment]
You can limit the read length use `-l sequence_len` to discard those reads cut by sliding window

**Comment by wyzhangMPI** [comment]
Hello,
    Sorry if my question is confusiong. In brief, I have questions:
     1) Could fastp do the trimming low-quality bases (Ns or bases with Q<20) from base to base for both ends of the read?
     2) How the "--cut_by_quality5/3" option in fastp is implemented? If the low-quality bases are in the beginning, would all the read be removed like in the Trimmomatic, or just clip off the low-quality part?

**Comment by sfchen** [comment]
Answers:
1, fastp can do low-quality bases trimming in the front or the end, with `--cut_by_quality5` or `--cut_by_quality3`
2, read is clipped, not discarded entirely
