### ISSUE TITLE
--adapter_sequence specifies multiple adapter sequences

### ISSUE THREAD

**Issue by xf78** [OpenGene/fastp#249]
Hi dear team ,
fastp is power tools for NGS data QC，i use the --detect_adapter_for_pe parameter for my PE data,but the adapter not be trim from my data view by fastqc,so i am going to  use --adapter_sequence specifies adapter sequences,but i am confuse that if i want to specifies multiple adapter sequences,how could i give this parameter,just like i ant to trim adapter TGTGTATAAGAGACAG and AGATGTGTATAAGAGACAG from R1 data,and trim the same adapter sequences for R2 data ,Looking forward to your reply,thanks!

**Comment by sfchen** [comment]
You can  add both  adapter sequence to a FASTQ file, and specify the file name by `--adapter_fasta`

**Comment by xf78** [comment]
thanks@sfchen,my fastp version is below 0.20,so i update my fastp to version  0.20.1,and now it's can run with --adapter_fasta, but the results may not be accurate, the adapter "CTGTCTCTTATACACATCT" in my data, after process by fastp,the data is alse enrich the adapter,below ids my linux command:

![图片](https://user-images.githubusercontent.com/13416926/79442328-024fc800-800b-11ea-9dd9-7b2426036c49.png)
then i use fastqc view the result, but the adapter content is alse high:
![图片](https://user-images.githubusercontent.com/13416926/79442864-acc7eb00-800b-11ea-852d-b7f3eef9459f.png)

and i am alse try with "detect_adapter_for_pe",but it can not work, None of the data was removed.
there are my fastq data file and adapter file（sorry for that i don't konw how to upload this issue）,i paste my files as follows:
fastq content:
@E00528:603:H7HKCCCX2:1:1101:2260:72139
TCTCCGAGCCCACTGTCTCTTATACACATCTCCGAGCCCACGAGACGCCAATGTATCTCGTATGCCGTCTTCTGCTTGAAAAAATCGATGAAGGAGGGGGACCCTCGGGTGCGGGGGGAAGTCAGAGATCGGACGGCGCTGTGAGCGCTG
+
AAFFFJAJJJJJJJJ<J77JFFJJJJJFJJJJJJJJFJJJJJJJJJJJJJFJJJJJJ-<FJJJJJJJJJJJAJJJJJJJFJJJJ-<7-7--<7<-77--7-77----7A-77--7-77----7----77-777--7-7--7--77---7-
@E00528:603:H7HKCCCX2:1:1101:2270:54471
GTGTATAAGAGACAGCTGTCTCTTATACACATCTCCGAGCCCACGAGACGCCAATGTATCTCGTATGCCGTCTTCTGCTTGAAAAAAGAGACGGTCACCCACAGGCCAACGATGGCGCCTCCTCATGGCGCACGCGTGGGAGCTGGCGCG
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJFFJJJJJJJJJJJJJJJJJJJJJJJJJ7---------7---7--------7<----77-7--7--7---7-----7--7--7--7---7-
@E00528:603:H7HKCCCX2:1:1101:2270:57038
GTATAAGAGACAGCTGTCTCTTATACACATCTCCGAGCCCACGAGACGCCAATGTATCTCGTATGCCGTCTTCTGCTTGAAAAAATACTGGGGGGCGCGGGTACGACGCCGGCCGGGATCGTAAATGGCGTCTGGTCCGTCGTGAGACGG
+
A<AFFJJJJJJJJJJJJJJJJJJFJJJJJJFJJJJJJJJJJJJJJJJJJJJFJJJFFFFFJJJJJJJJJJJJJ<FFJFJJJJJJJ--<7777--------7-----77------777--------7---777---7-7-7--7--7-7--
@E00528:603:H7HKCCCX2:1:1101:2270:58761
CTGTCTCTTATACCTGTCTCTTATACACATCTCCGAGCCCACGAGACGCCAATGTATCTCGTATGCCGTCTTCTGCTTGAAAAAAGAGAAAGTAGGGTGTGAACGGCCAAGGAGGACGGAGGCGGATGCCGGTAGGGTATGGGTATCGTA
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJFJJJJJJJJJJFJJJJJ<-----<----777--7<-<FA--7----A--77A77--<-77A-777---------------7-
@E00528:603:H7HKCCCX2:1:1101:2270:58796
TCTCTGTCCATCACCAACTCCTGGAGCCTACTCAAATTCATGGCCATTGAGTCGGTGATGCCATCCAACCATCTCGTCCTCTGTCATCCCCTTCTCCTGCCACCTTCAATCTCTCCCAGCACTGTCTCTTATACACATCTCCGAGCCCAC
+
A--FFFJFJFJJJJFJJFJFJJJFA<AAAFJFJJJJJJJJJJJJJJJ7JJJ7F7JJFAAF<-FAJ<7F<<AJAFFAFAFFJJJFJJJJJJJFJJJJJFJJJJJJJJJJJJJJJFFJFF<F<JFJJJAFFJJJJJJJFAJFAJF7FFJFJJ
@E00528:603:H7HKCCCX2:1:1101:2270:61222
AGAGACAGCTGTCTCTTATACACATCTCCGAGCCCACGAGACGCCAATGTATCTCGTATGCCGTCTTCTGCTTGAAAAAAAGTACAAGAAGGAACGATAAAATAAAGATCAGGGGTGAATAATCGCAGCGTGGGCAAAGGTGAGATGTAA
+
AAAFFJJJJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJ-<FFJJJJJJJJJJJJJJJJJJJJJJJ<7-7-----------7-7--77----77<7--7---7-7---------7---------7-----7-----
@E00528:603:H7HKCCCX2:1:1101:2270:61855
CGCCTACCCCAGATGTGAGTGGAACCATACAAAAACTGTCTCTTATACACATCTCCGAGCCCACGAGACGCCAATGTATCTCGTATGCCGTCTTCTGCTTGAAAAAACCCGCCGGCCTCCCCCCACCCAGAACCAAGCTCCGCCTGACCT
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJAJJJJAFJJJJJJJJJJJJJJJJJJJJJJJJJ--<-77----7AA--77-------7-7--7--7------7---
@E00528:603:H7HKCCCX2:1:1101:2270:64738
ACCTTAGGGAGGCGGGAAGTGAACTTCTTGATGGGGTCACGCGAAGCCCTGTCTCTTATACACATCTCCGAGCCCACGAGACGCCAATGTATCTCGTATGCCGTCTTCTGCTTGAAAAAAATTTTTTTTAATAATAGGGCAACCACCGAG
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJ-FJJJJJJJJJJJJJJJJJJJJJJJJ7<<AJJJJAJ-<-----77<--7--F----
@E00528:603:H7HKCCCX2:1:1101:2270:66320
ATAAGAGACAGCTGTCTCTTATACACATCTCCGAGCCCACGAGACGCCAATGTATCTCGTATGCCGTCGTCTGCTTGAAAAAAATGGGGGGGGGGTGGGGGGGGGCTCGGTGGGGCGGCGGTGCGTGCTCCGGCGTGAGCGTGGGCCTGC
+
AAFFFJJJJJJJJJ7JFJJJJJJJJJJJJJJJJJJJJJJAJJJJJJJJJJ7JJFJJ--AJFA<F<JAJ-77FJJJJF7F<AFF7<--7777-777--7AAJ-A77-7-77--777<F<-7A77-77A---7-A-----------7---7-
@E00528:603:H7HKCCCX2:1:1101:2270:70363
GATTAATAATGTTGTGTTAGTTTCAGCTGTACAGCATAGTGCTGTCTCTTATACACATCTCCGAGCCCACGAGACGCCAATGTATCTCGTATGCCGTCTTCTGCTTGAAAAAATAAACGATCGCGGCGGCTGCGGCTTTGCCCACGTTGC
+
AAAFFJJJJJJJFJAJJJJJFJAJJJJ<JJFJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJFJJJJJJJJJJJFJJJJJJFJJJJJJJ--7------777---7--7<7-7--7A-77----7--

adapter file content:

>PrefixNX/1
AGATGTGTATAAGAGACAG
>PrefixNX/2
AGATGTGTATAAGAGACAG
>Trans1
TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
>Trans1_rc
CTGTCTCTTATACACATCTGACGCTGCCGACGA
>Trans2
GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
>Trans2_rc
CTGTCTCTTATACACATCTCCGAGCCCACGAGAC

i have used the Trimmomatic trim this file and view result by fastqc,and it show that have no adapter,but i do not like Trimmomatic,my pipeline use by fastp,because fastp is powerful in my other projects, so any suggestions this this? Looking forward to your reply,thanks!

**Comment by AnnaSyme** [comment]
Are your reads overlapping? The help information shows this:

```
--adapter_sequence               the adapter for read1. For SE data, if not specified, the adapter will be auto-detected. For PE data, this is used if R1/R2 are found not overlapped. (string [=auto])
```

So I interpret that to mean that if the reads are not overlapping, then there will be no auto-detection of adapters. 

I might be wrong though!

**Comment by xf78** [comment]
@sfchen @AnnaSyme ,thanks for your help, the fastp work perfect know,i did not refresh my result directory,this is my fault,thanks for your help!!!

**Comment by sfchen** [comment]
Ok, good, please close this issue.
