### ISSUE TITLE
PolyG trimming?

### ISSUE THREAD

**Issue by mht85** [OpenGene/fastp#25]
Hello,

Thanks for the program. I'm working with NovaSeq data currently and would like to try out the polyG trimming. After trimming, it looks like fastp still retains reads with 8 or less Gs at the ends of reads. Is that a default set by fastp and what is the reason for doing so? Any way I can change the number of G's fastp lets through its filter?

Cheers,
Mun

**Comment by mht85** [comment]
It would be nice to have the option to adjust that setting. Would also be great to have the count included in the report? Just a suggestion. Thanks for the software by the way. May I know when the next version will be released?

**Comment by sfchen** [comment]
Next revision will come in two weeks.

**Comment by sfchen** [comment]
With the latest version in the master branch, you can use `--poly_g_min_len` to change the minimum length requirement for polyG detection. By default it's 10.

**Comment by sfchen** [comment]
Any update? Have you tried the new fastp from http://opengene.org/fastp/fastp ?
