### ISSUE TITLE
Question about duplication level

### ISSUE THREAD

**Issue by sumageb** [OpenGene/fastp#254]
Hi,
I first time handling the fastq files so I used fastp for the preprocessing of one of the paired-end data. This software is super fast. Thanks for building this.  I received 18.64% duplicated reads, I am wondering if this software removes all duplicates? Another question is that is there a duplication level that is not acceptable e.g. indicates the sample is poor?

**Comment by sfchen** [comment]
Normally 18.64% duplication is ok.

The duplication is just estimated, but not removed.

I may develop a new feature to remove duplicated reads

**Comment by sumageb** [comment]
Thanks a lot.
