### ISSUE TITLE
[Feature request] Process a part of reads only

### ISSUE THREAD

**Issue by Gerde** [OpenGene/fastp#260]
Hi， 
   In some case, we want to process only a part of reads instead of the whole reads in fastq file, such as the top 1000000 reads of each fastq file, this cant help us to quickly get an overview of the reads quality , and this can also be used as an datasize controller of reads which used in downstream analysis.
   Thanks a lot!

Best,
Gerde

**Comment by sfchen** [comment]
Hi, it's already supported in fastp.

Please use `--reads_to_process` option

**Comment by sfchen** [comment]
Hi, it's already supported in fastp.

Please use `--reads_to_process` option
