### ISSUE TITLE
adding only report option

### ISSUE THREAD

**Issue by manuelsmendoza** [OpenGene/fastp#279]
May it be possible to add an option to run only the quality checking and generate the report?

**Comment by KimBioInfoStudio** [comment]
hi, @manuelsmendoza
 could u try a workaround 1st on a Linux platform?
```
fastp -i  R1.fa -o /dev/null 
```

**Comment by sfchen** [comment]
The `-o/-O` options are optional. If you only want the QC reports, just DO NOT specify `-o/-O`.

**Comment by manuelsmendoza** [comment]
Many thanks!
