### ISSUE TITLE
Content of  rRNA

### ISSUE THREAD

**Issue by alibumi** [OpenGene/fastp#28]
HI, if I want know  the content of rRNA, fastp ,can it be calculated?

**Comment by sfchen** [comment]
Hi, I think the better way to calculate rRNA content is mapping the reads to rRNA regions.

**Comment by alibumi** [comment]
Hi, thank you for your answer.Would it be possible to add this function？

**Comment by sfchen** [comment]
I will develop a new tool for QC of SAM/BAM/CRAM files. This new tool will provide such function.
