### ISSUE TITLE
fastp for mac os

### ISSUE THREAD

**Issue by Roleren** [OpenGene/fastp#288]
Hey, In my R package ORFik I use fastp combined with STAR to align data, as this is the fastest combo I can find. But sadly mac users need to do their own trimming since fastp is not supported on mac os. Any plans to make it run on Mac ? :)

**Comment by cafeblue** [comment]
fastp is a great package. Sorry for my ad. We have an R version of fastp named Rfastp, which is a wrap of fastp. 

https://github.com/RockefellerUniversity/Rfastp

Rfastp can also be found in nightly built bioconductor.

**Comment by sfchen** [comment]
@Roleren fastp is supported on Mac OS X. Actually it was first developed on my MacBook.

**Comment by KimBioInfoStudio** [comment]
@Roleren  could u try the latest code,  I have just built on a macOS success with the following toolchains 
```
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by Roleren** [comment]
Sry for being unclear, I meant the pre-compiled binaries, since what I did was just to wget the precompiled binary and run that. But @cafeblue do you have some speed statistics to show the R version is still fast, then the R version will work even on windows I guess ?

**Comment by KimBioInfoStudio** [comment]
@Roleren  Pls check #287 #286 ,  fastp can build success cross win, Linux, macOS and arm Linux now,  if u prefer a precompiled binary, pls build for each platform, or u can chose add fastp  as a submodule and  build in place when install your R package

**Comment by Roleren** [comment]
Oh, I did not know that, I see the PR is not merged yet with the info. Thanks for the heads up. Let me know more about the fastp R package run time statistics then I will close the issue.

**Comment by KimBioInfoStudio** [comment]
@cafeblue  @Roleren  would u like add fastp as submodule in your own project and add your project  link to fastp repo s readme let more people known? @sfchen  what s your suggestion?

**Comment by cafeblue** [comment]
@Roleren We did very little modification on fastp source code to generate Rfastp, theoretically, Rfastp runs as fast as fastp. We tested Rfastp on linux, MacOS and Windows, it works fine on all these three platform. 

@KimBioInfoStudio Your suggestion sounds great! I will try to link Rfastp to fastp.

**Comment by KimBioInfoStudio** [comment]
@cafeblue  good idea, but i mean you should give credit to fastp firstly ...

**Comment by Roleren** [comment]
Thanks for the info, I will close this issue, I have the answers for my questions.
