### ISSUE TITLE
Galaxy wrapper & commit to Tool Shed

### ISSUE THREAD

**Issue by BigTA78** [OpenGene/fastp#29]
Would love a Galaxy wrapper so it can be used in place of trimmomatic in our current workflows

**Comment by mblue9** [comment]
@BigTA78 good news - your wish has been granted https://github.com/galaxyproject/tools-iuc/pull/1763

**Comment by sfchen** [comment]
@mblue9 big thanks for your contributions.

**Comment by mblue9** [comment]
Big thanks to YOU @sfchen and your team! I've just started trying fastp and think it's great. It feels like I was trying to search with a small penlight and now I've been handed a torch - I can see more! Thanks a lot :smile:
