### ISSUE TITLE
What comes first: trimming or Quality filtering ? 

### ISSUE THREAD

**Issue by rezenman** [OpenGene/fastp#294]
Hey, 
I generally use the pipeline for both trimming and filtering, 
When trimming I generally use global trimming to remove a certain number of bases from beginning and end,
For the quality filtering, I filter by n = 0 bases and percentage of the read which is under a certain quality score.
I wondered if I use them both, what comes first trimming or filtering? 
Thanks!

**Comment by sfchen** [comment]
Trimming comes first.
