### ISSUE TITLE
installation issue on CentOS6.9

### ISSUE THREAD

**Issue by wdecoster** [OpenGene/fastp#3]
Hi,

This looks like a great tool and I would like to give it a try, but I encountered an issue when attempting to install it. This issue might be due to our old server, which is a CentOS6.9 with gcc 4.8.2. Are there other system parameters you want to know? Installation went fine on my own Ubuntu 17.10.

I downloaded the release 0.5.0 (the same happens after cloning from GitHub), and executed `make`:

```
g++ -std=c++11 -g -I./inc -O3 -c  src/adaptertrimmer.cpp -o obj/adaptertrimmer.o
g++ -std=c++11 -g -I./inc -O3 -c  src/evaluator.cpp -o obj/evaluator.o
g++ -std=c++11 -g -I./inc -O3 -c  src/fastqreader.cpp -o obj/fastqreader.o
g++ -std=c++11 -g -I./inc -O3 -c  src/filter.cpp -o obj/filter.o
g++ -std=c++11 -g -I./inc -O3 -c  src/filterresult.cpp -o obj/filterresult.o
g++ -std=c++11 -g -I./inc -O3 -c  src/htmlreporter.cpp -o obj/htmlreporter.o
g++ -std=c++11 -g -I./inc -O3 -c  src/jsonreporter.cpp -o obj/jsonreporter.o
g++ -std=c++11 -g -I./inc -O3 -c  src/main.cpp -o obj/main.o
g++ -std=c++11 -g -I./inc -O3 -c  src/options.cpp -o obj/options.o
g++ -std=c++11 -g -I./inc -O3 -c  src/overlapanalysis.cpp -o obj/overlapanalysis.o
g++ -std=c++11 -g -I./inc -O3 -c  src/peprocessor.cpp -o obj/peprocessor.o
g++ -std=c++11 -g -I./inc -O3 -c  src/processor.cpp -o obj/processor.o
g++ -std=c++11 -g -I./inc -O3 -c  src/read.cpp -o obj/read.o
g++ -std=c++11 -g -I./inc -O3 -c  src/seprocessor.cpp -o obj/seprocessor.o
g++ -std=c++11 -g -I./inc -O3 -c  src/sequence.cpp -o obj/sequence.o
g++ -std=c++11 -g -I./inc -O3 -c  src/stats.cpp -o obj/stats.o
g++ -std=c++11 -g -I./inc -O3 -c  src/threadconfig.cpp -o obj/threadconfig.o
g++ -std=c++11 -g -I./inc -O3 -c  src/unittest.cpp -o obj/unittest.o
g++ -std=c++11 -g -I./inc -O3 -c  src/writer.cpp -o obj/writer.o
g++ ./obj/adaptertrimmer.o ./obj/evaluator.o ./obj/fastqreader.o ./obj/filter.o ./obj/filterresult.o ./obj/htmlreporter.o ./obj/jsonreporter.o ./obj/main.o ./obj/options.o ./obj/overlapanalysis.o ./obj/peprocessor.o ./obj/processor.o ./obj/read.o ./obj/seprocessor.o ./obj/sequence.o ./obj/stats.o ./obj/threadconfig.o ./obj/unittest.o ./obj/writer.o  -lz -lpthread -o fastp
./obj/peprocessor.o: In function `PairEndProcessor::initOutput()':
/home/wdecoster/bin/fastp-0.5.0/src/peprocessor.cpp:32: undefined reference to `gzbuffer'
/home/wdecoster/bin/fastp-0.5.0/src/peprocessor.cpp:35: undefined reference to `gzbuffer'
./obj/fastqreader.o: In function `FastqReader::getBytes(unsigned long&, unsigned long&)':
/home/wdecoster/bin/fastp-0.5.0/src/fastqreader.cpp:38: undefined reference to `gzoffset'
collect2: error: ld returned 1 exit status
make: *** [fastp] Error 1
```

Do you have suggestions on how to fix this?

Cheers,  
Wouter

**Comment by sfchen** [comment]
Your `zlip` is too old that it doesn't have functions like `gzbuffer` or `gzoffset`.  

You can update the `zlip`, or just download the binary distribution from http://opengene.org/fastp/fastp , and run `chmod a+x fastp` to make it executable.

**Comment by wdecoster** [comment]
Alright, thanks for the quick reply.

Running fastp on a fastq.gz file of nanopore data throws an error, not sure why:


```
$ fastp -t 20 -i fail/fastq_runid_fff19c6dcf86112967c3df0777ebeddda1109a40_1.fastq.gz -q 8 -l 5000 -o out
Detecting adapter for single end input...
No adapter detected

terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Aborted (core dumped)
```

Perhaps would be more appropriate in a separate thread, but do you think it would be possible to have fastp read from stdin and write to stdout?

**Comment by sfchen** [comment]
Thanks for your information.

I compiled that binary on Ubuntu, and seems it is not working on centOS.

I recompiled one in CentOS, you can download it from: http://opengene.org/fastp/fastpcentos

And another option is to update your old zlib, then compile by your self.

**Comment by sfchen** [comment]
And I also haven't tried any nanopore data, could you send me one or upload one here? (You can upload only first 1000 lines)

**Comment by wdecoster** [comment]
I'll test fastp again. I attached 1000 reads of [E.coli data](http://lab.loman.net/2017/03/09/ultrareads-for-nanopore/), but you can find plenty more publicly available, e.g.
https://github.com/nanopore-wgs-consortium/NA12878
[nanopore.fastq.gz](https://github.com/OpenGene/fastp/files/1472580/nanopore.fastq.gz)

**Comment by wdecoster** [comment]
fastp works fine now!
