### ISSUE TITLE
FASTP output fails to align using STAR

### ISSUE THREAD

**Issue by roni-fultheim** [OpenGene/fastp#309]
Hi, I have tried to trim and filter reads  by length using Fastp, but to no avail. 

The program runs successfully, but my downstream alignment results is near-zero aligment percentage (using STAR, a popular RNA-seq aligner) .
I cannot see any problem in Fastp's output FASTQ format, and using other programs the same samples are successfuly aligned after trimming and length filtering. 
Any input on the matter would be appreciated, once this is resolved I would like to incorporate Fastp in all my analysis pipelines.

Example of reads which could not be aligned after processing:
**Mate 1**
`@SRR3184286.sra.1259451 1259451 length=100
GCCTGAGCACACACACACATTCCACACGCATCATTAAAGGATAGCCATTTATTCTTCATAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGT`
`+SRR3184286.sra.1259451 1259451 length=100
BBBFFFFFFFFFFIIIIIIF0BFIIIFIIIIIIIIIIIIIIIIFIIIFIIIIIIIIIIIIIIIIIFFFFFFFFFFFFFFFFFFFBBBFFBFFFFF`
`@SRR3184286.sra.1259452 1259452 length=100
TCTCAACACCCGCCCCCCCCATGTTTAAACTTTGTGCCTTTGACCATCTCTTAGGTCTAATGATATTTTATGCAAACAGTTCTTGGCCCCCTGAA`
`+SRR3184286.sra.1259452 1259452 length=100
<BBBBBBBBBBFFBFFIFFFF<<FFF<BF<BFFB<<<B<BB<BB7B<<0<BB''<07<<0B070<BBBBFBBBF<<0700<<0<0''00077000`
**Mate 2**
`@SRR3184286.sra.1259451 1259451 length=100
GCCTGAGCACACACACACATTCCACACGCATCATTAAAGGATAGCCATTTATTCTTCATAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGT
+SRR3184286.sra.1259451 1259451 length=100
BBBFFFFFFFFFFIIIIIIF0BFIIIFIIIIIIIIIIIIIIIIFIIIFIIIIIIIIIIIIIIIIIFFFFFFFFFFFFFFFFFFFBBBFFBFFFFF
@SRR3184286.sra.1259452 1259452 length=100
TCTCAACACCCGCCCCCCCCATGTTTAAACTTTGTGCCTTTGACCATCTCTTAGGTCTAATGATATTTTATGCAAACAGTTCTTGGCCCCCTGAA
+SRR3184286.sra.1259452 1259452 length=100
<BBBBBBBBBBFFBFFIFFFF<<FFF<BF<BFFB<<<B<BB<BB7B<<0<BB''<07<<0B070<BBBBFBBBF<<0700<<0<0''00077000`

And after processing: 
**Mate 1**
`@SRR3184286.sra.1259451 0:N:  00
GCCTGAGCACACACACACATTCCACACGCATCATTAAAGGATAGCCATTTATTCTTCATAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGT`
`+`
`BBBFFFFFFFFFFIIIIIIF0BFIIIFIIIIIIIIIIIIIIIIFIIIFIIIIIIIIIIIIIIIIIFFFFFFFFFFFFFFFFFFFBBBFFBFFFFF`
`@SRR3184286.sra.1259452 0:N:  00`
`TCTCAACACCCGCCCCCCCCATGTTTAAACTTTGTGCCTTTGACCATCTCTTAGGTCTAATGATATTTTATGCAAACAGTTCTTGGCCCCCTGAA`
`+`
`<BBBBBBBBBBFFBFFIFFFF<<FFF<BF<BFFB<<<B<BB<BB7B<<0<BB''<07<<0B070<BBBBFBBBF<<0700<<0<0''00077000`
**Mate 2**
`@SRR3184286.sra.1259451 1:N:  00
GCCTGAGCACACACACACATTCCACACGCATCATTAAAGGATAGCCATTTATTCTTCATAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGT`
`+`
`BBBFFFFFFFFFFIIIIIIF0BFIIIFIIIIIIIIIIIIIIIIFIIIFIIIIIIIIIIIIIIIIIFFFFFFFFFFFFFFFFFFFBBBFFBFFFFF`
`@SRR3184286.sra.1259452 1:N:  00`
`TCTCAACACCCGCCCCCCCCATGTTTAAACTTTGTGCCTTTGACCATCTCTTAGGTCTAATGATATTTTATGCAAACAGTTCTTGGCCCCCTGAA`
`+`
`<BBBBBBBBBBFFBFFIFFFF<<FFF<BF<BFFB<<<B<BB<BB7B<<0<BB''<07<<0B070<BBBBFBBBF<<0700<<0<0''00077000`

My command:
`fastp -i SR_1.fastq -I SR_1.fastq -o SR_1.trim95.fastq -O SR_2.trim95.fastq --length_required 95 -Q -b 95 -B 95 -A`

Thank you
@bgruening 
@sfchen

**Comment by sfchen** [comment]
Could you please attach the log of failure of STAR program?

**Comment by roni-fultheim** [comment]
The program does not fail, but simply aligns under 1% of the reads. Using a different trimming program, the preprocessed reads had over 80% alignment. Only ~400 reads are aligned, from a 1317000 read pool.
I tried to look at the FASTQ format, used two different versions of Fastp and removed all possible dependancies, but nothing seemed to help. 
Perhaps you have an idea why. 

[SRR3184285Log.out.txt](https://github.com/OpenGene/fastp/files/5736335/SRR3184285Log.out.txt)
[SRR3184285Log.final.out.txt](https://github.com/OpenGene/fastp/files/5736336/SRR3184285Log.final.out.txt)

**Comment by sfchen** [comment]
-             Number of reads unmapped: too short |	1308174
-                  % of reads unmapped: too short |	99.33%
-                 Number of reads unmapped: other |	366
-                      % of reads unmapped: other |	0.03%

**Comment by sfchen** [comment]
Could you upload the HTML report of fastp?

**Comment by roni-fultheim** [comment]
I apologize, I reran the program now using the newest version and everything works fine.
Is it possible to update the version in conda?
Thank you
