### ISSUE TITLE
Add verbose output option (-V)

### ISSUE THREAD

**Issue by tseemann** [OpenGene/fastp#32]
When I run `fastp` there is *no output* until the end.

I would like to see what is happening.  
Would it be possible to add some progress messages?
`-V` / `--verbose`

Thanks

**Comment by sfchen** [comment]
Good idea. I will implement verbose mode.

Thank you, Torsten.

**Comment by sfchen** [comment]
Implemented

**Comment by tseemann** [comment]
Great, thank you.

**Comment by sk-sahu** [comment]
Is there a way to redirect `-V / --verbose` to a file (for logging purpose)?

I tried with bash builtin variables `stdout($1)`, `stderr($2)` and both(&) , But it doesn't seems to work.

Seems like `stdout` uses to redirect cleaned fastq to other tools as per the manual.
