### ISSUE TITLE
HTML report integration into MultiQC

### ISSUE THREAD

**Issue by c-guzman** [OpenGene/fastp#35]
One of the great things about FastQC is that MultiQC can be used to integrate all the quality control data into a single useful HTML.

Is this sort of integration available for Fastp or will it be implemented in the future?

**Comment by sfchen** [comment]
I think the integration is applicable, but the priority of this task is not very high.

**Comment by mblue9** [comment]
Hopefully it might happen over here: https://github.com/ewels/MultiQC/issues/669

**Comment by guidohooiveld** [comment]
For the archive: Fastp integration in MultiQC works with MultiQC version 1.6 dev0; I have just done this. See here: `https://github.com/ewels/MultiQC/blob/master/CHANGELOG.md#multiqc-version-history`

### MultiQC Version History
MultiQC v1.6dev

Some of these updates are thanks to the efforts of people who attended the NASPM 2018 MultiQC hackathon session. Thanks to everyone who attended!
New Modules:
    [fastp](https://github.com/OpenGene/fastp)
        An ultra-fast all-in-one FASTQ preprocessor (QC, adapters, trimming, filtering, splitting...)
        Module started by [@florianduclot](https://github.com/florianduclot/) and completed by [@ewels](https://github.com/ewels/)
   [Long Ranger](https://support.10xgenomics.com/genome-exome/software/pipelines/latest/what-is-long-ranger)
        Works with data from the 10X Genomics Chromium. Performs sample demultiplexing, barcode processing, alignment, quality control, variant calling, phasing, and structural variant calling.
        Module written by [@remiolsen](https://github.com/remiolsen/)

<<snip>>

**Comment by sfchen** [comment]
Big thanks for all of your efforts!
