### ISSUE TITLE
UMI FUNCTION ERROR

### ISSUE THREAD

**Issue by kir1to455** [OpenGene/fastp#352]
When I use fastp to trim my adapt ,it's ok.
However, when I use it to cut the UMI , it brings my some errors.
Here is the errors:
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
Aborted (core dumped)

**Comment by GuoFengWang** [comment]
how do you slove this problem?
