### ISSUE TITLE
fastp does not read bash variable

### ISSUE THREAD

**Issue by bowmanjeffs** [OpenGene/fastp#356]
Hello, I'm attempting to run fastp like this:

`READ1=test_R1`
`READ2=test_R2`
`fastp -i $READ1.fastq.gz -I $READ2.fastq.gz -o $READ1.qc.fastq.gz -O $READ2.qc.fastq.gz`

However, fastp ignores the variables and attempts to find ".fastq.gz".  I'm using the precompiled Linux binary.  Guessing this is not the intended behavior so reporting here.

**Comment by KimBioInfoStudio** [comment]
Hi @bowmanjeffs  could u try use "" to  surround  the variables like following
```bash
READ1=test_R1
READ2=test_R2
fastp -i "$READ1.fastq.gz" -I "$READ2.fastq.gz" -o "$READ1.qc.fastq.gz" -O "$READ2.qc.fastq.gz"
```

**Comment by sfchen** [comment]
I cannot reproduce this issue.

**Comment by rocpengliu** [comment]
this works for me
READ1=test_R1
READ2=test_R2
fastp -i ${READ1}.fastq.gz -I ${READ2}.fastq.gz -o ${READ1}.qc.fastq.gz -O ${READ2}.qc.fastq.gz

**Comment by bowmanjeffs** [comment]
Curly brackets did the trick, thanks!  Weirdly quotes did not.
