### ISSUE TITLE
Paired-end output files are shuffled

### ISSUE THREAD

**Issue by jakobnissen** [OpenGene/fastp#386]
When running `fastp` on input files and using the trimmed results to align with `bwa`, I get the following error:
`[mem_sam_pe] paired reads have different names: "M03704:23:000000000-JWCTN:1:2108:20369:8375", "M03704:23:000000000-JWCTN:1:2110:20520:13940"`.

I can then see that the forward and reverse files are in a different order:
```
ngs/test/run2$ head -1 tmp/trim/01/*.fq
==> tmp/trim/01/fw.fq <==
@M03704:23:000000000-JWCTN:1:2105:26234:19243 1:N:0:36

==> tmp/trim/01/rv.fq <==
@M03704:23:000000000-JWCTN:1:1104:7450:12048 2:N:0:36
```
I use version 0.23.2 from Conda.
I'll see if I can make a minimal example

**Comment by jakobnissen** [comment]
This was a mistake on my part - fastp seems to work fine. Sorry for the noise.

**Comment by YeGuoZJU** [comment]
> This was a mistake on my part - fastp seems to work fine. Sorry for the noise.

How to solve it?
