### ISSUE TITLE
BAM support

### ISSUE THREAD

**Issue by berguner** [OpenGene/fastp#39]
Hello,

We are using unmapped bam files for storing and archiving our sequence data. It would be really nice if fastp can take bam files as input and output fastq/bam files.

Best,
Bekir

**Comment by sfchen** [comment]
Actually I am going to kick off another project to build a comprehensive mapping file QC tool, which will work for BAM/SAM/CRAM.

But this mapping QC tool will be majorly designed for mapped BAM/SAM/CRAM, not for unmapped bam.

I remember that unmapped bam need larger space and will discard some information (some information in the first line of 4-line FASTQ record). What's the biggest benefit for using unmapped bam to store FASTQ files?

Although it's designed and promoted by BROAD, I still saw a lot of debates about it. And I would like to listen to your considerations before we can start unmapped bam support.

Thanks
Shifu

**Comment by berguner** [comment]
Our primary concern is to keep metadata specific to Illumina sequencing run such as RTA software version, instrument model, SBS kit version etc. You can add this in the bam header but you can't do that with fastq files. What is more, we can archive the multiplexed bam files and delete Illumina run folders. If we expperience a problem with barcodes, it is much easier to rerun demultiplexing on bam files instead of `.tar.gz` BCL files. bam files might take a bit more space but we don't think it is important considering their added benefit.

IMHO, you can simply use HTSlib to read bam files and process them just like the reads that you get from fastq files. You can check this unmapped bam file as an example:
https://drive.google.com/file/d/1j1Yjy1zU1F8dPpf-lQVkoP3FkK--FOqL/view?usp=sharing

I am not sure if there is any information that we lose by using bam files, can you please explain a bit more?

Best,
Bekir

**Comment by Coppini** [comment]
Another check on this, @sfchen. Is there any plan to have uBAM support on fastp natively?

On your concern about file sizes, [uBAM's are actually smaller than FASTQ.GZ files (and uCRAMs even smaller)](https://ubinfie.github.io/2024/06/06/switch-to-bam.html):
```
-rw-------. 1 user users 81M May 30 20:03 unmapped.bam
-rw-------. 1 user users 55M May 31 09:18 unmapped.cram
-rw-------. 1 user users 55M Dec  6  2019 1.fastq.gz
-rw-------. 1 user users 63M Dec  6  2019 2.fastq.gz
```

Having support for uBAM/uCRAM files would indeed be very useful to start moving into using these "better optimized" formats for file storage in the future of bioinformatics. Currently, we have to convert uBAMs to interleaved FASTQ files and pass that on to fastp, but having native support would be a lot better :)
