### ISSUE TITLE
Not an Issue but a function request

### ISSUE THREAD

**Issue by BenoitFiset** [OpenGene/fastp#4]
Hi,

  would it be nice to have an option to add a report name at the top of the report, Just before the summary. I use the -h option and this specified name added to the top of the report would help or a new option -R  Report name included in generated report (string [= reportname])

Thanks,

B.

**Comment by sfchen** [comment]
Good point, will be implemented in coming releases.

**Comment by BenoitFiset** [comment]
Hi,

  no pressure, but have any insight on implementation time frame ?

Thanks

**Comment by sfchen** [comment]
Will make it done today :)

**Comment by sfchen** [comment]
Implemented.

Use `-R` or `--report_title` to change the report title.

**Comment by sfchen** [comment]
Hi @BenoitFiset , do you have any further suggestion? If not, we can close this issue.

**Comment by BenoitFiset** [comment]
Sorry for delay to answer. Getting ready to do a run of 100 files soon, I'll update soon if all is fine.

**Comment by sfchen** [comment]
Is it good to close this issue?

**Comment by BenoitFiset** [comment]
Yep it works.

Thanks can close.
