### ISSUE TITLE
Request to add QIAseq miRNA to known adapters

### ISSUE THREAD

**Issue by robsyme** [OpenGene/fastp#438]
The QIAseq miRNA NGS 3’ Adapter is not included in the list of known adapters. It would be great to use `fastp` on miRNA data without having to manually specify adapter sequence. 

The QIAseq miRNA adapter sequence is:
```
AACTGTAGGCACCATCAAT
```

Documentation: https://www.qiagen.com/kr/resources/faq?id=f12b85b4-df4f-43b5-9e82-a4fd0ddbdcc0&lang=en

**Comment by apeltzer** [comment]
Added a PR in #440 that should add this to the header file
