### ISSUE TITLE
Feature Request: automatic quality score conversion

### ISSUE THREAD

**Issue by cviner** [OpenGene/fastp#44]
Perhaps this tool already supports this, but if not, it would be very useful to implement automatic quality score format detection and conversion. For further details, please see my [analogous request](https://github.com/shenwei356/seqkit/issues/18) for [SeqKit](https://github.com/shenwei356/seqkit), for which this has now been [fully-implemented](https://github.com/shenwei356/seqkit/issues/18#issuecomment-321825742).

**Comment by sfchen** [comment]
fastp automatically converts phred64 scoring to phred33 scoring. If you only want to do quality score conversion, you can disable all filtering/trimming by specifying `-A -Q -L -G`. The command must look like:
```
fastp -i in.R1.fq -I in.R2.fq -o out.R1.fq -O out.R2.fq --phred64 -A -Q -L -G
```

**Comment by cviner** [comment]
@sfchen Glad to hear that and thanks for these details!

I was, however, referring to a complete implementation of _all_ possible [FASTQ quality encodings](https://en.wikipedia.org/wiki/FASTQ_format#Encoding), including detection and accounting for the specific max/min values, special codes, non-linearities, etc. This is what was implemented within [SeqKit](https://github.com/shenwei356/seqkit), after some [discussion](https://github.com/shenwei356/seqkit/issues/18).

**Comment by tseemann** [comment]
"you can disable all filtering/trimming by specifying -A -Q -L -G"

Can you add that to he documentation?
