### ISSUE TITLE
Overrepresented sequences belong to highly expressed chloroplast-related genes

### ISSUE THREAD

**Issue by ocho** [OpenGene/fastp#45]
How can one keep these overrepresend sequences? For example I used this sample "SRR3100237"

fastp -i SRA/out/SRR3100237_1.fastq.gz \
-I SRA/out/SRR3100237_2.fastq.gz \
-o FASTP/SRR3100237_1_trim.fastq.gz \
-O FASTP/SRR3100237_2_trim.fastq.gz \
-h Reports/SRR3100237 -R "SRR3100237" -l 36 -c -g -p -M 30 -w 6 -5 -3

[fastp-report_SRR3100237.zip](https://github.com/OpenGene/fastp/files/1833673/fastp-report_SRR3100237.zip)

looking forward!

**Comment by sfchen** [comment]
Overrepresented sequences are not discarded.

The overrepresentation analysis just give a profiling of these overrepresented sequences.
