### ISSUE TITLE
why trimmed fq.gz files are larger than the raw ones

### ISSUE THREAD

**Issue by YulongNiu** [OpenGene/fastp#48]
Hi,
I noticed that after the fastp trimming, `fastp -g -p -c`, the size of trimmed fq.gz files are larger than the raw ones. There are about 0.55 M reads were filtered.

**Comment by sfchen** [comment]
It's caused by the compression level difference.

```
-z, --compression                  compression level for gzip output (1 ~ 9). 1 is fastest, 9 is smallest, default is 2. (int [=2])
 ```

You can set `-z 6` to improve the compression ratio. It will run a bit slower, but the output will be smaller.

**Comment by YulongNiu** [comment]
Thanks!
