### ISSUE TITLE
why "--cut_by_quality3"  reduce reads counts

### ISSUE THREAD

**Issue by liwg123** [OpenGene/fastp#49]
hi sfchen:

     I want to known why "-3" option will reduce  reads passed filters.
fastp -i SRR1770413_1.fastq -I SRR1770413_2.fastq -q 20 -u 20  -o out.SRR1770413_1.fastq -O out.SRR1770413_2.fastq
![image](https://user-images.githubusercontent.com/38343206/38720381-a476106a-3f28-11e8-9037-4d58b4355fb3.png)

fastp -i SRR1770413_1.fastq -I SRR1770413_2.fastq -q 20 -u 20 -3 -o out.SRR1770413_1.fastq -O out.SRR1770413_2.fastq
![image](https://user-images.githubusercontent.com/38343206/38720352-89ba0bbe-3f28-11e8-99c6-0d8f1f3a2eb7.png)

**Comment by sfchen** [comment]
Your data is strange, PE 300?

Can you post the complete HTML files here?

**Comment by liwg123** [comment]
@sfchen 
yes, the data is 300 PE, download from  SRA
![image](https://user-images.githubusercontent.com/38343206/38790260-8d4e1e18-4172-11e8-91a0-11de339e8f71.png)

the two html reports are in attached file
[fastp.zip](https://github.com/OpenGene/fastp/files/1913897/fastp.zip)

thank you!

**Comment by sfchen** [comment]
Thanks, I will try to look into the data when I have time.

**Comment by sfchen** [comment]
This seems like a small bug about quality filtering, I just fixed it, could you please try to build fastp with latest code on master. Or download http://opengene.org/fastp/fastp to test.

**Comment by liwg123** [comment]
Thank you for your prompt reply.

the reads counts is the same for the two conditions "-q 20 -u 20" ,"-q 20 -u 20 -s 3", but the total bases After filtering  is identity too, there is no per read cutting by quality in tail (3').

when combined the two filters, Is there a priority for filtering?

**Comment by sfchen** [comment]
You should use "-q 20 -u 20 -3", not "-q 20 -u 20 -s 3"

**Comment by sfchen** [comment]
Can you close this issue right now?
