### ISSUE TITLE
Demultiplexing of samples

### ISSUE THREAD

**Issue by coolkom** [OpenGene/fastp#53]
Hi,
Thanks for this nice tool. How would it be possible to demultiplex samples based on unique barcode or unique combination of barcode + adapter?

Cheers,
Komlan.

**Comment by sfchen** [comment]
Demultiplexing is usually done by bcl2fastq, what's your exact need for demultiplexing using fastp?

**Comment by coolkom** [comment]
Actually I use the STACKS pipeline to analyse RADseq data, from the raw fastq files to the final vcf file. One of the first steps is to clean (remove adaptor contamination and low quality reads) and demultiplex the reads into samples. The library is usually made by ligating unique barcode to digested DNA or combination of barcode + index. So by giving the barcode exact sequence (or barcode + index sequences), the reads are split into different samples before going through the following steps. This seems to be all in one tool. So I wonder if it would be possible to do this demultiplexing step (as in the Stacks pipeline) also within it, by giving the sequences of barcodes (usually 5 to 12 bp or even a bit longer).

**Comment by coolkom** [comment]
The bcl2fastq Illumina program would demultiplex samples based on universal index short sequences, but the obtained demultiplexed "samples" are often a mix or samples that would be separated based on barcodes at the beginning of the sequences (read1 for example, between the adaptor and the start of actual DNA sequence).

**Comment by sfchen** [comment]
Understood.

You mean that multiple samples share the same `sample index`, and can only be demultiplexed using the barcode from the inserted DNA (read1 / read2)

**Comment by coolkom** [comment]
Yes correct.

**Comment by sfchen** [comment]
You should prepare a file to describe the mapping of barcode and sample, right? Could you upload a sample of this file?

**Comment by coolkom** [comment]
Yes, sure.
Here are two examples. The file barcode6.txt contain the simplest case. A barcode and the corresponding sample name on the same line (tab separated). The second file barcodesPool1.txt contains a combinatorial case, a sample corresponding to a combination of barcode and an index. In the case of the second file, often, the files were already demultiplexed with the Illumina software and the index tags are added to the IDs of the sequences (so barcode is inline and index is in the ID name). It can also happen that the Illumina first demultiplexing is not done, in which case the second file is even more important since you will have all combinations of barcodes + indices.
Please note that in some cases, the barcodes can be of variable lengths within the same big file.

[barcode6.txt](https://github.com/OpenGene/fastp/files/1941573/barcode6.txt)

[barcodesPool1.txt](https://github.com/OpenGene/fastp/files/1941577/barcodesPool1.txt)

**Comment by sfchen** [comment]
OK.

This feature will be added to road map, but it will not be implemented very soon. I need to complete some other more important functions.

**Comment by coolkom** [comment]
Ok. Thanks!

**Comment by sfchen** [comment]
You can use OpenGene/defq for this task.
