### ISSUE TITLE
how to specify index in adapter sequence? 

### ISSUE THREAD

**Issue by housw** [OpenGene/fastp#54]
Hi, 
I want to remove adapters for different libraries, how can I specify the index in the adapter_sequence_r2? It seems 'N' is not allowed - 
```
ERROR: the adapter <adapter_sequence_r2> can only have bases in {A, T, C, G}, but the given sequenceR2 is: GATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
```

Thanks in advance!

**Comment by sfchen** [comment]
You can just specify the first part:
`GATCGGAAGAGCACACGTCTGAACTCCAGTCAC`
This is long enough for fastp to detect the adapters.
