### ISSUE TITLE
Phred score converter

### ISSUE THREAD

**Issue by mossishahi** [OpenGene/fastp#61]
how is it possible to use fastp only for converting phred64 to phred33 score, not any trim or quality control?

**Comment by sfchen** [comment]
add -Q -A -G option to disable quality filtering/trimming, adapter trimming, and polyG trimming

**Comment by mossishahi** [comment]
thanks
it worked with a line of code like this:
`fastp -A -Q -G --phred64 -i Lib1.fq -I Lib2.fq -o Lib1.fq -O Lib2.fq `

**Comment by sfchen** [comment]
Yes, correct.
