### ISSUE TITLE
How to upgrade fastp or uninstall in Ubuntu?

### ISSUE THREAD

**Issue by biofisherman** [OpenGene/fastp#63]
I want to upgrade to latest version and how could I do this?
I tried to use `sudo apt-get remove fastq`  or `sudo apt-get remove fastq` and none of them worked.

Thanks,
Weiyan

**Comment by sfchen** [comment]
How did you installed fastp previously?

fastp is not integrated in apt-get server. But you can upgrade fastp by following methods:

1. download the latest code, make and make install.
2. download the latest binary from http://opengene.org/fastp/fastp, `chmod a+x ./fastp`, find the old fastp path by `which fastp`, then copy the new fastp to replace the old one.

**Comment by biofisherman** [comment]
Thanks for your quick response.
I followed this method:
`wget http://opengene.org/fastp/fastp
chmod a+x ./fastp`

I will try your suggestion.
Best,

Weiyan

**Comment by sfchen** [comment]
Did that work?

**Comment by biofisherman** [comment]
Sorry for late reply. There are all working! 
Thank you very much for your help!
