### ISSUE TITLE
cut_by_quality3

### ISSUE THREAD

**Issue by rojinsafavi** [OpenGene/fastp#65]
I am trying to do 3' trimming based on the  quality of the 3' end. I would like to know how exactly --cut_by_quality3  work? Does it start by looking at the quality per base from the 3' end, and it keeps trimming the 3' tail until it reaches a good quality read?

Right now I'm using a command like this:
(my data is PE)

fastp -i  mse-1-CTL_R1_001.fastq -I mse-1-CTL_R2_001.fastq -q 20 --cut_by_quality3 20 -t 20 -l 50 -o mse-1-CTL_R1_001_Q_A.fastq -O mse-1-CTL_R2_001_Q_A.fastq -h mse-1-CTL_001.html

**Comment by sfchen** [comment]
It's based on sliding window.
See https://github.com/OpenGene/fastp#per-read-cutting-by-quality-score
