### ISSUE TITLE
try make by using mingw an Error 

### ISSUE THREAD

**Issue by KimBioInfoStudio** [OpenGene/fastp#66]
# try make by using mingw an Error 
## version 
v0.17
##############################################################################
g++ -std=c++11 -g -I./inc  -O3 -c src/filter.cpp -o obj/filter.o
In file included from src/processor.h:4:0,
                 from src/filter.cpp:1:
src/options.h:266:10: error: declaration of '__iob_func' as array of references
     bool stdout;
          ^
make: *** [Makefile:27: obj/filter.o] Error 1

##############################################################################
## suggestion 
stdout is one of reserved word of C++, replace this declaration with someone else

**Comment by sfchen** [comment]
Thanks, I will make a change

**Comment by sfchen** [comment]
Please try the latest code

**Comment by KimBioInfoStudio** [comment]
thx  for your help, make pass on windows 10 pro 64bit  paltform with mingw64
