### ISSUE TITLE
I have a error in make &make install

### ISSUE THREAD

**Issue by yumenxx** [OpenGene/fastp#67]
the error as below
=================================================================
[root@localhost fastp-0.17.0]# make
g++ -std=c++11 -g -I./inc  -O3 -c src/adaptertrimmer.cpp -o obj/adaptertrimmer.o
g++ -std=c++11 -g -I./inc  -O3 -c src/basecorrector.cpp -o obj/basecorrector.o
g++ -std=c++11 -g -I./inc  -O3 -c src/duplicate.cpp -o obj/duplicate.o
g++ -std=c++11 -g -I./inc  -O3 -c src/evaluator.cpp -o obj/evaluator.o
g++ -std=c++11 -g -I./inc  -O3 -c src/fastqreader.cpp -o obj/fastqreader.o
g++ -std=c++11 -g -I./inc  -O3 -c src/filter.cpp -o obj/filter.o
g++ -std=c++11 -g -I./inc  -O3 -c src/filterresult.cpp -o obj/filterresult.o
g++ -std=c++11 -g -I./inc  -O3 -c src/htmlreporter.cpp -o obj/htmlreporter.o
g++ -std=c++11 -g -I./inc  -O3 -c src/jsonreporter.cpp -o obj/jsonreporter.o
g++ -std=c++11 -g -I./inc  -O3 -c src/main.cpp -o obj/main.o
g++ -std=c++11 -g -I./inc  -O3 -c src/nucleotidetree.cpp -o obj/nucleotidetree.o
g++ -std=c++11 -g -I./inc  -O3 -c src/options.cpp -o obj/options.o
g++ -std=c++11 -g -I./inc  -O3 -c src/overlapanalysis.cpp -o obj/overlapanalysis.o
g++ -std=c++11 -g -I./inc  -O3 -c src/peprocessor.cpp -o obj/peprocessor.o
g++ -std=c++11 -g -I./inc  -O3 -c src/polyx.cpp -o obj/polyx.o
g++ -std=c++11 -g -I./inc  -O3 -c src/processor.cpp -o obj/processor.o
g++ -std=c++11 -g -I./inc  -O3 -c src/read.cpp -o obj/read.o
g++ -std=c++11 -g -I./inc  -O3 -c src/seprocessor.cpp -o obj/seprocessor.o
g++ -std=c++11 -g -I./inc  -O3 -c src/sequence.cpp -o obj/sequence.o
g++ -std=c++11 -g -I./inc  -O3 -c src/stats.cpp -o obj/stats.o
g++ -std=c++11 -g -I./inc  -O3 -c src/threadconfig.cpp -o obj/threadconfig.o
g++ -std=c++11 -g -I./inc  -O3 -c src/umiprocessor.cpp -o obj/umiprocessor.o
g++ -std=c++11 -g -I./inc  -O3 -c src/unittest.cpp -o obj/unittest.o
g++ -std=c++11 -g -I./inc  -O3 -c src/writer.cpp -o obj/writer.o
g++ ./obj/adaptertrimmer.o ./obj/basecorrector.o ./obj/duplicate.o ./obj/evaluator.o ./obj/fastqreader.o ./obj/filter.o ./obj/filterresult.o ./obj/htmlreporter.o ./obj/jsonreporter.o ./obj/main.o ./obj/nucleotidetree.o ./obj/options.o ./obj/overlapanalysis.o ./obj/peprocessor.o ./obj/polyx.o ./obj/processor.o ./obj/read.o ./obj/seprocessor.o ./obj/sequence.o ./obj/stats.o ./obj/threadconfig.o ./obj/umiprocessor.o ./obj/unittest.o ./obj/writer.o -o fastp  -lz -lpthread
./obj/fastqreader.o: In function `FastqReader::getBytes(unsigned long&, unsigned long&)':
/home/xiaolezhu/yuelei/fastp-0.17.0/src/fastqreader.cpp:32: undefined reference to `gzoffset'
./obj/peprocessor.o: In function `PairEndProcessor::initOutput()':
/home/xiaolezhu/yuelei/fastp-0.17.0/src/peprocessor.cpp:40: undefined reference to `gzbuffer'
/home/xiaolezhu/yuelei/fastp-0.17.0/src/peprocessor.cpp:43: undefined reference to `gzbuffer'
collect2: 错误：ld 返回 1
make: *** [fastp] 错误 1
===============================================================
how to solve it?

**Comment by sfchen** [comment]
install zlib first
