### ISSUE TITLE
Suggested/Minimum memory requirement

### ISSUE THREAD

**Issue by srynobio** [OpenGene/fastp#70]
I noticed from past runs that fastp suggests `1-16 cpus` per run, but is their a suggested/minimum memory requirement?  I could not find it your docs.

**Comment by sfchen** [comment]
fastp requires a little RAM. 2G is more than enough.

BTW, usually 2 or 3 cpus are enough.  fastp is I/O limited since it runs too fast than read/write.

**Comment by srynobio** [comment]
@sfchen thanks for your reply, on the memory requirements.  Are you suggesting that 2-3 cpus is as efficient as 16?
