### ISSUE TITLE
fastp hangs when used in a docker enviroment.

### ISSUE THREAD

**Issue by srynobio** [OpenGene/fastp#72]
I have both a question and an issue.

Currently I am using fastp via Docker on AWS.  I'm having an issue where fastp will hang for a indiscriminate amount of time.  I've added runtime limits to the docker environment, but this is a less then ideal method to overcome this issue.  If you or anyone has any insight or solutions it would be much appreciated.

<img width="1270" alt="fastpscreen" src="https://user-images.githubusercontent.com/1106139/42714626-1299b220-86b1-11e8-8465-515143a1b8d7.png">

**Comment by sfchen** [comment]
Which version of fastp are you using? Have you tried the same data, same command with a local server?

**Comment by sfchen** [comment]
Does it always hang, or sometime?

**Comment by srynobio** [comment]
I know its a recent version of `fastp` as I build the dock about 2 weeks ago.  I have notice it has issue with both WGS and WES data.

**Comment by sfchen** [comment]
Ok, I will test fastp on AWS dockers. I have ever docker on local server and it worked well.

**Comment by srynobio** [comment]
Just to note, I have seen this behavior while fastp is running on our local HPC environment as well.

**Comment by timedreamer** [comment]
I notice this too. I used fastp 0.18.1 installed via pip. 191 jobs submitted to HPC through SLURM. 110 jobs finished in 5min. However, rest of jobs hangs there for the entire node time (I tried 1h and 3h). The trimmed files seem already generated. But the reports never generate and jobs keep going. 

Any ideas? Thanks!

**Comment by sfchen** [comment]
@srynobio for your local HPC env, was fastp ran in docker or not?

@srynobio @timedreamer have you ever tried v0.17 or older? Did it hang with these older versions?

Did the hang happen randomly, or specified to some files?

Since I cannot reproduce the hang in my local env, these information will greatly help me to debug.

Thank you very much.

**Comment by srynobio** [comment]
Sorry for the late reply @sfchen.

The jobs I run on our local HPC are not currently dockerized. 

And currently I'm using: 

```
fastp: an ultra-fast all-in-one FASTQ preprocessor
version 0.12.5
```
The hangs appear to happen completely at random as far as I can tell.

**Comment by sfchen** [comment]
@srynobio can you try the new version in the local HPC?

Since now I can sometime reproduce this issue in some cloud-based docker, but cannot reproduce this issue with local servers. So it's quiet hard to debug it.

Your information will be much helpful for debugging.

**Comment by sfchen** [comment]
Hi all,

I added an option `-V` or `--verbose` to support the verbose mode. In this mode, some log information will be written to STDOUT, so that it will give the clue of where fastp hangs.

Could you please update to the new v0.19.0, and add `-V` to your commands to have some tests?

Thank you very much.

**Comment by timedreamer** [comment]
Thank you for looking into this. I just used `fastp 0.19.0` on the same files with `--verbose`. It seems they hangs at different stages. Three log files were attached (file names are not the original ones). Agains no new reads into the trimmed gz files, but no reports generated and jobs stay on.

Thanks.

1. file1
[12:53:46] start to load data
[12:53:50] loaded 1M reads
[12:53:53] loaded 2M reads
[12:53:59] loaded 3M reads
[12:54:5] loaded 4M reads
[12:54:10] loaded 5M reads
[12:54:16] loaded 6M reads
[12:54:21] loaded 7M reads
[12:54:27] loaded 8M reads
[12:54:32] loaded 9M reads
[12:54:37] loaded 10M reads
[12:54:43] loaded 11M reads
[12:54:48] loaded 12M reads
[12:54:54] loaded 13M reads
[12:54:59] loaded 14M reads
[12:55:5] loaded 15M reads
[12:55:11] loaded 16M reads
[12:55:16] loaded 17M reads
[12:55:21] all reads loaded
[12:55:21] thread 0 data processing completed
[12:55:21] thread 0 finished
[12:55:24] /data/trim_fastq/test1.fq.gz writer finished

2. file2
[12:53:54] start to load data
[12:53:57] loaded 1M reads
[12:54:2] loaded 2M reads
[12:54:8] loaded 3M reads
[12:54:13] loaded 4M reads
[12:54:18] loaded 5M reads
[12:54:24] loaded 6M reads
[12:54:29] loaded 7M reads
[12:54:35] loaded 8M reads
[12:54:40] loaded 9M reads
[12:54:46] loaded 10M reads
[12:54:51] loaded 11M reads
[12:54:57] loaded 12M reads
[12:55:2] loaded 13M reads
[12:55:6] all reads loaded

3. File 3
[12:53:52] start to load data
[12:53:55] loaded 1M reads
[12:54:0] loaded 2M reads
[12:54:5] loaded 3M reads
[12:54:10] loaded 4M reads
[12:54:16] loaded 5M reads
[12:54:21] loaded 6M reads
[12:54:25] loaded 7M reads
[12:54:31] loaded 8M reads
[12:54:35] all reads loaded
[12:54:35] thread 1 data processing completed
[12:54:35] thread 1 finished
[12:54:37] test2.fq.gz writer finished

**Comment by sfchen** [comment]
Hi all,

I revised the threading model of fastp. Please help to update to the latest v0.19.1, test it and update here.

I hope this time it will not hang. If it still hangs, please also paste the log here.

Thank you very much.

**Comment by sfchen** [comment]
Good news.

With the latest v0.19.1, fastp didn't hang in my cloud-based docker env. I think it will also work in your servers.

Thanks
Shifu

**Comment by timedreamer** [comment]
Awesome. Just tried with the same files and they quickly finished! 
Thank you Shifu!

**Comment by sfchen** [comment]
That's great, @srynobio how about you?

**Comment by srynobio** [comment]
@sfchen I will update and report back soon.

**Comment by sfchen** [comment]
v0.19.3 released. This version should reserved all deadlock issue.

Please upgrade to this release version, since v0.19.1 may result in unequal R1/R2.

**Comment by srynobio** [comment]
I've updated my version and will reopen if the issue persists.  Thanks @sfchen

**Comment by hmkim** [comment]
I faced issue for this similarly.

I used the fastp 0.20.1 with thread option. (thread: 6)

My fastq.gz file size is very small. (Read1: 9.7M, Read2: 11M)

I tried to rerun the fastp. It finished at once.

**Comment by sfchen** [comment]
new version will fix this issue, please wait for v0.23.0

**Comment by astatham** [comment]
Hi - we only noticed the issue today with a freshly built docker images containing v0.23.0 (this did not occur for us on v0.22.0)

**Comment by astatham** [comment]
@sfchen - my Dockerfile was downloading `http://opengene.org/fastp/fastp`, and running `fastp --version` reported v0.23.0; this was happening in the last 24 hours. Hope that helps!

**Comment by sfchen** [comment]
Is it reproducible? I mean the hang issue of v0.23.0. How big is the data? Single-end or paired-end?

I rewrote the threading and I/O modules, so v0.23.0 may be 1.5x faster as v0.22.0.

**Comment by jdwinkler-lanzatech** [comment]
We are still having a similar issue on 0.23.1. Should we upgrade to 0.23.2 instead?

**Comment by biofilos** [comment]
Hi, I still have the same problem in version 0.32.3
I think I figured how to reproduce this behavior (though I don't know why this is the case)
When running fastp in a container, the command will run if it is run by itself. However, when using Cromwell, the command is wrapped as
```bash
set -x
(
fastp command...
)
```
and then it will fail. Basically, when wrapping the command in `set -x ()`, fastp will hang. Interestingly, I have this problem only with ChIP-seq fastq files. I can run other analyses (RNA-seq, DNA-seq) even wrapped in `set -x ()` with no issues
Is there a workaround for this version?
Thanks
