### ISSUE TITLE
PE mode produces unequal amount of reads

### ISSUE THREAD

**Issue by shenwei356** [OpenGene/fastp#74]
Thanks for this cool tool, but the paired end mode seems do not support producing equal amount of reads or writing unpaired reads as separated files as trimmomatic does.

version: https://github.com/OpenGene/fastp/commit/89a9a5385d6913c85c1a41f2f557118178d36f20
data: too big to upload

**Comment by sfchen** [comment]
Thanks, I also noticed this bug in my alicloud servers. And strangely it worked well in my local server.

I just updated to code which may address this issue, can you help to test the latest code?

**Comment by sfchen** [comment]
This bug was introduced by a change of 3 days ago.

**Comment by shenwei356** [comment]
It's fixed. Thank you for rapid reply!
