### ISSUE TITLE
feature request: trimming to maximum length

### ISSUE THREAD

**Issue by cverwimp** [OpenGene/fastp#77]
Hi,

It would be nice to have an option to trim reads to a certain maximum length, similarly as [cutadapt -l](http://cutadapt.readthedocs.io/en/stable/guide.html#shortening-reads-to-a-fixed-length), but ultra-fast then of course :)

Thanks

**Comment by sfchen** [comment]
Good suggestion, I will implement it.

**Comment by sfchen** [comment]
Implemented.

* If you want to trim the reads to maximum length, you can specify `-b, --max_len1` for read1, and `-B, --max_len2` for read2. If `--max_len1` is specified but `--max_len2` is not, `--max_len2` will be same as `--max_len1`. For example, if `--max_len1` is specified and read1 is longer than `--max_len1`, `fastp` will trim read1 at its tail to make it as long as `--max_len1`.

Please note that the trimming for `--max_len` limitation will be applied at the last step. Following are fastp's processing steps that may orderly affect the read lengthes:
```
1, UMI preprocessing (--umi)
2, global trimming at front (--trim_front)
3, global trimming at tail (--trim_tail)
4, quality pruning at 5' (--cut_by_quality5)
5, quality pruning at 3' (--cut_by_quality3)
6, trim polyG (--trim_poly_g, enabled by default for NovaSeq/NextSeq data)
7, trim polyX (--trim_poly_x)
8, trim adapter by overlap analysis (enabled by default for PE data)
9, trim adapter by adapter sequence (--adapter_sequence, --adapter_sequence_r2. For PE data, this step is skipped if last step succeeded)
10, trim to max length (---max_len)
```

**Comment by cverwimp** [comment]
Great! Thank you!
