### ISSUE TITLE
Disable trimming of N's

### ISSUE THREAD

**Issue by lparsons** [OpenGene/fastp#78]
This is an excellent and very fast program for fastq processing. Im looking to use it as a fast way to move UMIs to the read name. However, despite using:

    --disable_adapter_trimming
    --disable_length_filtering
    --disable_quality_filtering
    --cut_mean_quality 0
    --disable_trim_poly_g

`fastp` still seems to be removing N's from the reads. This is problematic for our use case as it can change the start alignment position of the read. Is there a way to turn this off?

**Comment by sfchen** [comment]
fastp removes Ns from the start or end of the read, only if `--cut_by_quality5` or `--cut_by_quality3` is enabled.

Can you post the command, and paste some reads for testing?

**Comment by lparsons** [comment]
Hmmm... Well, I'm sure I ran into this, but I'm unable to replicate now. Perhaps I was misusing some option. If it comes up again, I'll be sure to post with an example.
