### ISSUE TITLE
Support UMI located in separate index read

### ISSUE THREAD

**Issue by lparsons** [OpenGene/fastp#80]
Perhaps this is already supported, but I'm having trouble figuring out how to get fastp to handle our specific case. We start with single end reads with dual indexes (so three fastq files). The first index is part of the sample barcode. The second index contains both a sample barcode sequence (used in conjunction with the first) and a UMI. The first 8 bases of the second index are barcode, and the last 8 bases are the UMI.

I'm fine with handling the demultiplexing outside of fastp, but I'd like to handle the UMI extraction with fastp. I see two issues:
1. There is no method to extract the UMI from later in the read (specifying `--trim_front2` performs the trimming *after* UMI extraction).
2. When specifying a second read, fastp treats the data as paired end. This isn't a huge issue, but does create some strange looking stats.

Any thoughts on how this could be accomplished would be appreciated.

**Comment by sfchen** [comment]
Probably you can read this closed issue: https://github.com/OpenGene/fastp/issues/23
