### ISSUE TITLE
fastp  memory usage and speed up

### ISSUE THREAD

**Issue by whiteorchid** [OpenGene/fastp#83]
![image](https://user-images.githubusercontent.com/6839620/44133485-95f69eee-a092-11e8-8d0d-377f1f3a0bcb.png)
Dear author,used the fastp for 158 G R1.fq and 158G R2.fq (`fastp -w 16 -i R1.fq -I R2.fq -o R1.clean.fq -O R2.clean.fq` takes about 2.5 h to accomplish ) may I ask if it's ok to give the tool more memory usage and processors so it can run much faster?

**Comment by sfchen** [comment]
It is I/O bounded.

To read and write 158G + 158G

**Comment by sfchen** [comment]
-w 4 is usually enough, and -w 16 will not be faster

**Comment by whiteorchid** [comment]
it seems the soft only use max mem of 1G, will it affect the IO to read and write?

**Comment by sfchen** [comment]
I/O means the disk read and write.

**Comment by whiteorchid** [comment]
sure, thanks for your mentor!

**Comment by ATpoint** [comment]
@sfchen Is the memory consumption predicatable? I had it on some samples (ATAC-seq) that memory was peaking up to > 8GB even with the `--dont_eval_duplication` enabled. Can you comment?
