### ISSUE TITLE
输出fq.gz结果文件尾部很多行乱码

### ISSUE THREAD

**Issue by Xingsl** [OpenGene/fastp#84]
陈总，您好！我最近使用fastp处理BGIseq500,Hiseq4000,MGIseq2000等多个平台测序数据。发现处理每种平台数据后的结果都存在尾部很多行乱码现象。请问你们遇见过这种情况吗？

**Comment by sfchen** [comment]
没有人汇报过相关问题。请问你的fastp版本是多少？

可否贴一下是怎样的乱码？

**Comment by Xingsl** [comment]
版本号是fastp 0.19.4
尾部一些行变成了这种，不知道是我使用参数不合适还是什么原因。
我在天河二号超算上的运行命令是：(time yhrun -N 1 -n 8 /..../bin/fastp -w 8  -j Report/Novaseq_74.json -h Report/Novaseq_74.html -R "Novaseq_74 fastp report" -i  /..../...-74_1.fq.gz -o /..../Cleandata/Novaseq_74_R1.fq.gz -I  /.../...-74_2.fq.gz -O /..../Cleandata/Novaseq_74_R2.fq.gz) 2>logfile/Novaseq_74.log.file
结果尾部乱码，但是软件也没有报错。
后几行：
<GAGAE5:1@GAC1/EFGEFGT58GFET58GFEFEFCT????G=GF/B/C5=9C@4>>0EDC=C/F=DA/FF/CT58GFEG=CBCLFT935CGGG2EG=CBEG=;B/G0FF=DD0BGG)>A-FBG?A;?BA:>>
CT5GEFGCF/???4BCGE854B8F/C4B3C6FC?<BEG5/43?F:9TB=6FC6F9ECF3?F:95FG7GCC5GEFBG8FT4CTTTTC1AGR@CBAB>DEAT)ET@5C5:7/1
FEFEFEGEFFGF3GF5F)G=F=FB35C@444/8DC3GF5C@4>EC9EFBG>A.<
EA/38GGF3GF3GF5G>A.<C@GCG>A.<G>G0=@EFG1FF?FT>5//644GEFED/1
FGTBG8FTGF01GGFF?TC7GCC544CT=CC5GEF3?F<BEG9G9TB/@6F4445C/FF
CF4::T4AEFFGG8B4F44G1G=CB601G=CF/???4BB8CCFGAGAE5:1@GAC9114FDG>CGFF=FBFEFCT??
D9>CEGD3GF5FDC=C/F=DA35FGFF
CF14ABD=D@FFFFF=FBFFBG>EFFEEEEEEGCG>A.<G>G0=@EFG1FF?FT>5//64B/8GCCFFG@TGFBAFGDA0
C@<@A:CCF79ECFFTC
CF4:ET,.CF794G94TBG8:TC6CFET8G/444CFET8CB=6FECF3?F<37B6A:AAAF3@F4:A:G1/EF3?F<3&FDF4CFB44F4CF5CGGCGD4C=GFFA=F0CGFE<BEGTD
TB=F=FBAFD6FFGE9/@9G@TF0DG3)84G???F5F)GGFTDGTTTTTTBA:FGTTTBA:FGTEFF:<GGFGAFG7GC9TB5BF/C437B6F79ECF@TGFBAFG8FTGF???BF4GFFACG/444
CC5F:95FG.<C@G442;C5?F1C/CB)8&>AA3G>C0CB=6F
BCCAC6CAGCGAA
TTC=ACC=EG.F/B=A=F0CF0CGFE=AGF:FCAE=GFG?=F=F&FDFFFGEF6FFG:TTDDA>AFGF/=F0CFF4<C5@E<>C,8C?T4EEC??B/)ET@:FGTTTBA:FGTEFF:<GGFGAFG7GC3TTGGF
=CC5GCT5?4:1@:
CC5BCCAC6CF3?FGCAGGF???BF=DA:CC5GCC5GCCT4EE>5BCCA4BF/4AF>FG4CF5CGGCGD444F4CF5C44F4CF5CGGCGD444F4C/8F3)15:1@GACFBGC@EA6=6@>A44T/8G6F
CFBGCEF2G7F4C1@FFFF>=DCBF=F:9TB5F:9598@;D9A/C=>GT:T40=@EFAFGDAF/C4DET,.TTTBAFG@T@;BFFBAFGAFGAF/C4=>GF==CBCGAFGCC544CF4:EGGF??GE6CTDAT?
FEFEFEGEF45/GCCCCC4AECFT1GGA/AFC5GEFECF1@81CCC-8:CA-DTB.9GCAG2,C(DB-;@G:D>5=>E2A9@<E4BG7GC9TB5BF
(END)

**Comment by sfchen** [comment]
0.19.4 是还没有正式发布的。

1，你能否用0.19.3重新测一下？
2，看看是不是天河系统的问题，你试一下在本地跑？
3，有没有你调度的命令中，让多个进程写了同一个数据？

为了国际化，我希望每 个Issue都是英文的

所以，这个issue我要马上关闭，请加我的微信 opengene 进行后续交流。
