### ISSUE TITLE
Enforce length limit by cutting residual nucleotides

### ISSUE THREAD

**Issue by dnieuw** [OpenGene/fastp#88]
Dear Shifu Chen,

Great talk yesterday at ECCB2018! I have been playing around with fastp on my data already and I found that fastp does not crop the read but discards the too long read when using the --length_limit option. My Iontorrent data contains technical-error-reads that are longer than the possible 400 nt. The phred score of these tails is high, however, so they will not be quality trimmed.
Would it be possible to add an option to crop the residual nucleotides of a too long read instead of discarding them?

**Comment by sfchen** [comment]
I will implement this feature in next release.

**Comment by sfchen** [comment]
Implemented.

* If you want to trim the reads to maximum length, you can specify `-b, --max_len1` for read1, and `-B, --max_len2` for read2. If `--max_len1` is specified but `--max_len2` is not, `--max_len2` will be same as `--max_len1`. For example, if `--max_len1` is specified and read1 is longer than `--max_len1`, `fastp` will trim read1 at its tail to make it as long as `--max_len1`.

Please note that the trimming for `--max_len` limitation will be applied at the last step. Following are fastp's processing steps that may orderly affect the read lengthes:
```
1, UMI preprocessing (--umi)
2, global trimming at front (--trim_front)
3, global trimming at tail (--trim_tail)
4, quality pruning at 5' (--cut_by_quality5)
5, quality pruning at 3' (--cut_by_quality3)
6, trim polyG (--trim_poly_g, enabled by default for NovaSeq/NextSeq data)
7, trim polyX (--trim_poly_x)
8, trim adapter by overlap analysis (enabled by default for PE data)
9, trim adapter by adapter sequence (--adapter_sequence, --adapter_sequence_r2. For PE data, this step is skipped if last step succeeded)
10, trim to max length (---max_len)
```
