### ISSUE TITLE
ERROR: thread number (--thread) should be 1  16, suggest 1  8

### ISSUE THREAD

**Issue by TainVelasco-Luquez** [OpenGene/fastp#89]
Dear @sfchen,

Firstly I want to congratulate your work, fastp is a great tool.

Secondly, my issue: I am running fastp as part of a Nextflow pipeline named [QUARS](https://github.com/TainVelasco-Luquez/QUARS), where I can use as many threads as the user specify, however, when threads' number is greater than 16 I get the following fastp error:

`ERROR: thread number (--thread) should be 1 ~ 16, suggest 1 ~ 8`

After reading the issue #13 I understand why the limit. However, such error keeps halting the whole pipeline execution. Is there any way to disable such limit?

I look forward to hearing from you.

Sincerely

@TainVelasco-Luquez

**Comment by sfchen** [comment]
I can change the error to warning in new version, but why you don't decrease the thread number?

8 threads are much more than enough since fastp is so fast

**Comment by cviner** [comment]
I just encountered this same issue. Ideally, `fastp` should simply adjust the number of threads accordingly, if necessary, and emit a warning documenting what occurred.

**Comment by sfchen** [comment]
Done, now you can try it with latest code, or download the latest prebuilt binary from http://opengene.org/fastp/fastp

Next release will include this change.

**Comment by TainVelasco-Luquez** [comment]
Excellent. 

Thank you for your answer and your package.

Tain.
