### ISSUE TITLE
mean length increasing after filtering

### ISSUE THREAD

**Issue by bernt-matthias** [OpenGene/fastp#92]
with 0.19.3 I see the following: 

```
mean length before filtering: 92bp, 93bp 
mean length after filtering: 93bp, 93bp
```

Seems odd.

**Comment by sfchen** [comment]
It may happen when you filter more short reads than long reads since short reads tend to have lower quality.

**Comment by bernt-matthias** [comment]
True -- should have realized this on my own :(. Thanks for the feedback.
