### ISSUE TITLE
Questions about the overlap correction.

### ISSUE THREAD

**Issue by chenatf** [OpenGene/fastp#96]
I have two questions:
1. why you do not correct the overlap reads if their mismatch is bigger than 5?  Your paper said it can reduce the false correction, but it didn't show any data to support these words. Your overlapanalysis program consider two conditions: (mismatch <5) or (mismatch >=5 and compare match region >50). I was very confused about you didn't correct the overlap reads if its (mismatch >=5 and compare match region > 50).
2. can we correct the base if one is in bad quality, the other may be not very good but much better than the   bad one, such as bigger than 5?

**Comment by sfchen** [comment]
I have two questions:

why you do not correct the overlap reads if their mismatch is bigger than 5? Your paper said it can reduce the false correction, but it didn't show any data to support these words. Your overlapanalysis program consider two conditions: (mismatch <5) or (mismatch >=5 and compare match region >50). I was very confused about you didn't correct the overlap reads if its (mismatch >=5 and compare match region > 50).
---- if too many mismatches exist, the confidence of the pair is really overlapped will be low. So then fastp will stop to correct them.

can we correct the base if one is in bad quality, the other may be not very good but much better than the bad one, such as bigger than 5?
----No. It may cause over-correction. But probably set them as N is a better idea.
