### ISSUE TITLE
No Duplication Rate Reported

### ISSUE THREAD

**Issue by doliv071** [OpenGene/fastp#98]
Hi all, thanks for the awesome tool and all your effort on developing it! 

I ran fastp with the `-q 15 -n 10 -l 15 --thread 6 -p -P 100` on paired end fastq files, but I don't get any duplication information in the html or json reports.

**Comment by sfchen** [comment]
What's your fastp version? Can you upload the HTML file here?

**Comment by doliv071** [comment]
Ah sorry, I did not do my due diligence, it looks like the bioconda channel I have available on our HPC is out of date and so I have v0.14.1 installed and I see that duplication rate was added in 0.15. I will update it. Thanks again.
